// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum CFuncMoverMove_t : uint
{
	MOVE_LOOP = 0x0,
	MOVE_OSCILLATE = 0x1,
	MOVE_STOP_AT_END = 0x2,
}
