// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum CNmTimeConditionNodeOperator_t : byte
{
	LessThan = 0x0,
	LessThanEqual = 0x1,
	GreaterThan = 0x2,
	GreaterThanEqual = 0x3,
}
