// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum EDestructiblePartDamagePassThroughType : uint
{
	Normal = 0x0,
	Absorb = 0x1,
	InvinciblePassthrough = 0x2,
}
