// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum EntityAttachmentType_t : uint
{
	eAbsOrigin = 0x0,
	eCenter = 0x1,
	eEyes = 0x2,
	eAttachment = 0x3,
}
