// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum ModelBoneFlexComponent_t : uint
{
	MODEL_BONE_FLEX_INVALID = 0xFFFFFFFF,
	MODEL_BONE_FLEX_TX = 0x0,
	MODEL_BONE_FLEX_TY = 0x1,
	MODEL_BONE_FLEX_TZ = 0x2,
}
