// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum MoodType_t : uint
{
	eMoodType_Head = 0x0,
	eMoodType_Body = 0x1,
}
