// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum NmCachedValueMode_t : uint
{
	OnEntry = 0x0,
	OnExit = 0x1,
}
