// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum ParticleOrientationSetMode_t : uint
{
	PARTICLE_ORIENTATION_SET_NONE = 0xFFFFFFFF,
	PARTICLE_ORIENTATION_SET_FROM_VELOCITY = 0x0,
	PARTICLE_ORIENTATION_SET_FROM_NORMAL = 0x1,
	PARTICLE_ORIENTATION_SET_FROM_ROTATIONS = 0x2,
}
