// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum PoseType_t : byte
{
	POSETYPE_STATIC = 0x0,
	POSETYPE_DYNAMIC = 0x1,
	POSETYPE_INVALID = 0xFF,
}
