// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum PulseValueType_t : uint
{
	PVAL_INVALID = 0xFFFFFFFF,
	PVAL_BOOL = 0x0,
	PVAL_INT = 0x1,
	PVAL_FLOAT = 0x2,
	PVAL_STRING = 0x3,
	PVAL_VEC3 = 0x4,
	PVAL_TRANSFORM = 0x5,
	PVAL_COLOR_RGB = 0x6,
	PVAL_EHANDLE = 0x7,
	PVAL_RESOURCE = 0x8,
	PVAL_SNDEVT_GUID = 0x9,
	PVAL_ENTITY_NAME = 0xA,
	PVAL_SCHEMA_PTR = 0xB,
	PVAL_TYPESAFE_INT = 0xC,
	PVAL_CURSOR_FLOW = 0xD,
	PVAL_ANY = 0xE,
	PVAL_SCHEMA_ENUM = 0xF,
	PVAL_COUNT = 0x10,
}
