// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum ValueRemapperInputType_t : uint
{
	InputType_PlayerShootPosition = 0x0,
	InputType_PlayerShootPositionAroundAxis = 0x1,
}
