// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum ValueRemapperRatchetType_t : uint
{
	RatchetType_Absolute = 0x0,
	RatchetType_EachEngage = 0x1,
}
