// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;

namespace CounterStrikeSharp.API.Core;

public enum WeaponAttackType_t : uint
{
	eInvalid = 0xFFFFFFFF,
	ePrimary = 0x0,
	eSecondary = 0x1,
	eCount = 0x2,
}
