// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class AttachmentHandle_t : NativeObject
{
    public AttachmentHandle_t (IntPtr pointer) : base(pointer) {}

	// m_Value
	[SchemaMember("AttachmentHandle_t", "m_Value")]
	public virtual byte Value
	{
		get { return Schema.GetValueType<byte>(this.Handle, "AttachmentHandle_t", "m_Value"); }
		set { Schema.SetValueType<byte>(this.Handle, "AttachmentHandle_t", "m_Value", value); }
	}

}
