// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class audioparams_t : NativeObject
{
    public audioparams_t (IntPtr pointer) : base(pointer) {}

	// localSound
	[SchemaMember("audioparams_t", "localSound")]
	public Span<Vector> LocalSound => Schema.GetFixedArray<Vector>(this.Handle, "audioparams_t", "localSound", 8);

	// soundscapeIndex
	[SchemaMember("audioparams_t", "soundscapeIndex")]
	public ref Int32 SoundscapeIndex => ref Schema.GetRef<Int32>(this.Handle, "audioparams_t", "soundscapeIndex");

	// localBits
	[SchemaMember("audioparams_t", "localBits")]
	public ref byte LocalBits => ref Schema.GetRef<byte>(this.Handle, "audioparams_t", "localBits");

	// soundscapeEntityListIndex
	[SchemaMember("audioparams_t", "soundscapeEntityListIndex")]
	public ref Int32 SoundscapeEntityListIndex => ref Schema.GetRef<Int32>(this.Handle, "audioparams_t", "soundscapeEntityListIndex");

	// soundEventHash
	[SchemaMember("audioparams_t", "soundEventHash")]
	public ref UInt32 SoundEventHash => ref Schema.GetRef<UInt32>(this.Handle, "audioparams_t", "soundEventHash");

}
