// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CBaseDoor : CBaseToggle
{
    public CBaseDoor (IntPtr pointer) : base(pointer) {}

	// m_angMoveEntitySpace
	[SchemaMember("CBaseDoor", "m_angMoveEntitySpace")]
	public virtual QAngle MoveEntitySpace
	{
		get { return Schema.GetValueType<QAngle>(this.Handle, "CBaseDoor", "m_angMoveEntitySpace"); }
		set { Schema.SetValueType<QAngle>(this.Handle, "CBaseDoor", "m_angMoveEntitySpace", value); }
	}

	// m_vecMoveDirParentSpace
	[SchemaMember("CBaseDoor", "m_vecMoveDirParentSpace")]
	public virtual Vector3 MoveDirParentSpace
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CBaseDoor", "m_vecMoveDirParentSpace"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CBaseDoor", "m_vecMoveDirParentSpace", value); }
	}

	// m_ls
	[SchemaMember("CBaseDoor", "m_ls")]
	public virtual locksound_t Ls => Schema.GetDeclaredClass<locksound_t>(this.Handle, "CBaseDoor", "m_ls");

	// m_bForceClosed
	[SchemaMember("CBaseDoor", "m_bForceClosed")]
	public virtual bool ForceClosed
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bForceClosed"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bForceClosed", value); }
	}

	// m_bDoorGroup
	[SchemaMember("CBaseDoor", "m_bDoorGroup")]
	public virtual bool DoorGroup
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bDoorGroup"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bDoorGroup", value); }
	}

	// m_bLocked
	[SchemaMember("CBaseDoor", "m_bLocked")]
	public virtual bool Locked
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bLocked"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bLocked", value); }
	}

	// m_bIgnoreDebris
	[SchemaMember("CBaseDoor", "m_bIgnoreDebris")]
	public virtual bool IgnoreDebris
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bIgnoreDebris"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bIgnoreDebris", value); }
	}

	// m_bNoNPCs
	[SchemaMember("CBaseDoor", "m_bNoNPCs")]
	public virtual bool NoNPCs
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bNoNPCs"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bNoNPCs", value); }
	}

	// m_eSpawnPosition
	[SchemaMember("CBaseDoor", "m_eSpawnPosition")]
	public virtual FuncDoorSpawnPos_t SpawnPosition
	{
		get { return Schema.GetValueType<FuncDoorSpawnPos_t>(this.Handle, "CBaseDoor", "m_eSpawnPosition"); }
		set { Schema.SetValueType<FuncDoorSpawnPos_t>(this.Handle, "CBaseDoor", "m_eSpawnPosition", value); }
	}

	// m_flBlockDamage
	[SchemaMember("CBaseDoor", "m_flBlockDamage")]
	public virtual float BlockDamage
	{
		get { return Schema.GetValueType<float>(this.Handle, "CBaseDoor", "m_flBlockDamage"); }
		set { Schema.SetValueType<float>(this.Handle, "CBaseDoor", "m_flBlockDamage", value); }
	}

	// m_NoiseMoving
	[SchemaMember("CBaseDoor", "m_NoiseMoving")]
	public virtual string NoiseMoving
	{
		get { return Schema.GetUtf8String(this.Handle, "CBaseDoor", "m_NoiseMoving"); }
		set { Schema.SetString(this.Handle, "CBaseDoor", "m_NoiseMoving", value); }
	}

	// m_NoiseArrived
	[SchemaMember("CBaseDoor", "m_NoiseArrived")]
	public virtual string NoiseArrived
	{
		get { return Schema.GetUtf8String(this.Handle, "CBaseDoor", "m_NoiseArrived"); }
		set { Schema.SetString(this.Handle, "CBaseDoor", "m_NoiseArrived", value); }
	}

	// m_NoiseMovingClosed
	[SchemaMember("CBaseDoor", "m_NoiseMovingClosed")]
	public virtual string NoiseMovingClosed
	{
		get { return Schema.GetUtf8String(this.Handle, "CBaseDoor", "m_NoiseMovingClosed"); }
		set { Schema.SetString(this.Handle, "CBaseDoor", "m_NoiseMovingClosed", value); }
	}

	// m_NoiseArrivedClosed
	[SchemaMember("CBaseDoor", "m_NoiseArrivedClosed")]
	public virtual string NoiseArrivedClosed
	{
		get { return Schema.GetUtf8String(this.Handle, "CBaseDoor", "m_NoiseArrivedClosed"); }
		set { Schema.SetString(this.Handle, "CBaseDoor", "m_NoiseArrivedClosed", value); }
	}

	// m_ChainTarget
	[SchemaMember("CBaseDoor", "m_ChainTarget")]
	public virtual string ChainTarget
	{
		get { return Schema.GetUtf8String(this.Handle, "CBaseDoor", "m_ChainTarget"); }
		set { Schema.SetString(this.Handle, "CBaseDoor", "m_ChainTarget", value); }
	}

	// m_OnBlockedClosing
	[SchemaMember("CBaseDoor", "m_OnBlockedClosing")]
	public virtual CEntityIOOutput OnBlockedClosing => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnBlockedClosing");

	// m_OnBlockedOpening
	[SchemaMember("CBaseDoor", "m_OnBlockedOpening")]
	public virtual CEntityIOOutput OnBlockedOpening => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnBlockedOpening");

	// m_OnUnblockedClosing
	[SchemaMember("CBaseDoor", "m_OnUnblockedClosing")]
	public virtual CEntityIOOutput OnUnblockedClosing => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnUnblockedClosing");

	// m_OnUnblockedOpening
	[SchemaMember("CBaseDoor", "m_OnUnblockedOpening")]
	public virtual CEntityIOOutput OnUnblockedOpening => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnUnblockedOpening");

	// m_OnFullyClosed
	[SchemaMember("CBaseDoor", "m_OnFullyClosed")]
	public virtual CEntityIOOutput OnFullyClosed => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnFullyClosed");

	// m_OnFullyOpen
	[SchemaMember("CBaseDoor", "m_OnFullyOpen")]
	public virtual CEntityIOOutput OnFullyOpen => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnFullyOpen");

	// m_OnClose
	[SchemaMember("CBaseDoor", "m_OnClose")]
	public virtual CEntityIOOutput OnClose => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnClose");

	// m_OnOpen
	[SchemaMember("CBaseDoor", "m_OnOpen")]
	public virtual CEntityIOOutput OnOpen => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnOpen");

	// m_OnLockedUse
	[SchemaMember("CBaseDoor", "m_OnLockedUse")]
	public virtual CEntityIOOutput OnLockedUse => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CBaseDoor", "m_OnLockedUse");

	// m_bLoopMoveSound
	[SchemaMember("CBaseDoor", "m_bLoopMoveSound")]
	public virtual bool LoopMoveSound
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bLoopMoveSound"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bLoopMoveSound", value); }
	}

	// m_bCreateNavObstacle
	[SchemaMember("CBaseDoor", "m_bCreateNavObstacle")]
	public virtual bool CreateNavObstacle
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bCreateNavObstacle"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bCreateNavObstacle", value); }
	}

	// m_isChaining
	[SchemaMember("CBaseDoor", "m_isChaining")]
	public virtual bool IsChaining
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_isChaining"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_isChaining", value); }
	}

	// m_bIsUsable
	[SchemaMember("CBaseDoor", "m_bIsUsable")]
	public virtual bool IsUsable
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseDoor", "m_bIsUsable"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseDoor", "m_bIsUsable", value); }
	}

	public virtual void IsUsablePropertyChanged() => Utilities.SetStateChanged(this, "CBaseDoor", "m_bIsUsable");
}
