// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CBaseCombatCharacter : CBaseFlex
{
    public CBaseCombatCharacter (IntPtr pointer) : base(pointer) {}

	// m_bForceServerRagdoll
	[SchemaMember("CBaseCombatCharacter", "m_bForceServerRagdoll")]
	public bool ForceServerRagdoll
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseCombatCharacter", "m_bForceServerRagdoll"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseCombatCharacter", "m_bForceServerRagdoll", value); }
	}

	// m_hMyWearables
	[SchemaMember("CBaseCombatCharacter", "m_hMyWearables")]
	public NetworkedVector<CHandle<CEconWearable>> MyWearables => Schema.GetDeclaredClass<NetworkedVector<CHandle<CEconWearable>>>(this.Handle, "CBaseCombatCharacter", "m_hMyWearables");

	// m_impactEnergyScale
	[SchemaMember("CBaseCombatCharacter", "m_impactEnergyScale")]
	public float ImpactEnergyScale
	{
		get { return Schema.GetValueType<float>(this.Handle, "CBaseCombatCharacter", "m_impactEnergyScale"); }
		set { Schema.SetValueType<float>(this.Handle, "CBaseCombatCharacter", "m_impactEnergyScale", value); }
	}

	// m_bApplyStressDamage
	[SchemaMember("CBaseCombatCharacter", "m_bApplyStressDamage")]
	public bool ApplyStressDamage
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseCombatCharacter", "m_bApplyStressDamage"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseCombatCharacter", "m_bApplyStressDamage", value); }
	}

	// m_bDeathEventsDispatched
	[SchemaMember("CBaseCombatCharacter", "m_bDeathEventsDispatched")]
	public bool DeathEventsDispatched
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBaseCombatCharacter", "m_bDeathEventsDispatched"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBaseCombatCharacter", "m_bDeathEventsDispatched", value); }
	}

	// m_strRelationships
	[SchemaMember("CBaseCombatCharacter", "m_strRelationships")]
	public string StrRelationships
	{
		get { return Schema.GetUtf8String(this.Handle, "CBaseCombatCharacter", "m_strRelationships"); }
		set { Schema.SetString(this.Handle, "CBaseCombatCharacter", "m_strRelationships", value); }
	}

	// m_eHull
	[SchemaMember("CBaseCombatCharacter", "m_eHull")]
	public Hull_t Hull
	{
		get { return Schema.GetValueType<Hull_t>(this.Handle, "CBaseCombatCharacter", "m_eHull"); }
		set { Schema.SetValueType<Hull_t>(this.Handle, "CBaseCombatCharacter", "m_eHull", value); }
	}

	// m_nNavHullIdx
	[SchemaMember("CBaseCombatCharacter", "m_nNavHullIdx")]
	public UInt32 NavHullIdx
	{
		get { return Schema.GetValueType<UInt32>(this.Handle, "CBaseCombatCharacter", "m_nNavHullIdx"); }
		set { Schema.SetValueType<UInt32>(this.Handle, "CBaseCombatCharacter", "m_nNavHullIdx", value); }
	}

	// m_movementStats
	[SchemaMember("CBaseCombatCharacter", "m_movementStats")]
	public CMovementStatsProperty MovementStats => Schema.GetDeclaredClass<CMovementStatsProperty>(this.Handle, "CBaseCombatCharacter", "m_movementStats");

}
