// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CBasePlayerPawn : CBaseCombatCharacter
{
    public CBasePlayerPawn (IntPtr pointer) : base(pointer) {}

	// m_pWeaponServices
	[SchemaMember("CBasePlayerPawn", "m_pWeaponServices")]
	public CPlayer_WeaponServices? WeaponServices => Schema.GetPointer<CPlayer_WeaponServices>(this.Handle, "CBasePlayerPawn", "m_pWeaponServices");

	// m_pItemServices
	[SchemaMember("CBasePlayerPawn", "m_pItemServices")]
	public CPlayer_ItemServices? ItemServices => Schema.GetPointer<CPlayer_ItemServices>(this.Handle, "CBasePlayerPawn", "m_pItemServices");

	// m_pAutoaimServices
	[SchemaMember("CBasePlayerPawn", "m_pAutoaimServices")]
	public CPlayer_AutoaimServices? AutoaimServices => Schema.GetPointer<CPlayer_AutoaimServices>(this.Handle, "CBasePlayerPawn", "m_pAutoaimServices");

	// m_pObserverServices
	[SchemaMember("CBasePlayerPawn", "m_pObserverServices")]
	public CPlayer_ObserverServices? ObserverServices => Schema.GetPointer<CPlayer_ObserverServices>(this.Handle, "CBasePlayerPawn", "m_pObserverServices");

	// m_pWaterServices
	[SchemaMember("CBasePlayerPawn", "m_pWaterServices")]
	public CPlayer_WaterServices? WaterServices => Schema.GetPointer<CPlayer_WaterServices>(this.Handle, "CBasePlayerPawn", "m_pWaterServices");

	// m_pUseServices
	[SchemaMember("CBasePlayerPawn", "m_pUseServices")]
	public CPlayer_UseServices? UseServices => Schema.GetPointer<CPlayer_UseServices>(this.Handle, "CBasePlayerPawn", "m_pUseServices");

	// m_pFlashlightServices
	[SchemaMember("CBasePlayerPawn", "m_pFlashlightServices")]
	public CPlayer_FlashlightServices? FlashlightServices => Schema.GetPointer<CPlayer_FlashlightServices>(this.Handle, "CBasePlayerPawn", "m_pFlashlightServices");

	// m_pCameraServices
	[SchemaMember("CBasePlayerPawn", "m_pCameraServices")]
	public CPlayer_CameraServices? CameraServices => Schema.GetPointer<CPlayer_CameraServices>(this.Handle, "CBasePlayerPawn", "m_pCameraServices");

	// m_pMovementServices
	[SchemaMember("CBasePlayerPawn", "m_pMovementServices")]
	public CPlayer_MovementServices? MovementServices => Schema.GetPointer<CPlayer_MovementServices>(this.Handle, "CBasePlayerPawn", "m_pMovementServices");

	// m_ServerViewAngleChanges
	[SchemaMember("CBasePlayerPawn", "m_ServerViewAngleChanges")]
	public NetworkedVector<ViewAngleServerChange_t> ServerViewAngleChanges => Schema.GetDeclaredClass<NetworkedVector<ViewAngleServerChange_t>>(this.Handle, "CBasePlayerPawn", "m_ServerViewAngleChanges");

	// v_angle
	[SchemaMember("CBasePlayerPawn", "v_angle")]
	public QAngle V_angle
	{
		get { return Schema.GetValueType<QAngle>(this.Handle, "CBasePlayerPawn", "v_angle"); }
		set { Schema.SetValueType<QAngle>(this.Handle, "CBasePlayerPawn", "v_angle", value); }
	}

	// v_anglePrevious
	[SchemaMember("CBasePlayerPawn", "v_anglePrevious")]
	public QAngle V_anglePrevious
	{
		get { return Schema.GetValueType<QAngle>(this.Handle, "CBasePlayerPawn", "v_anglePrevious"); }
		set { Schema.SetValueType<QAngle>(this.Handle, "CBasePlayerPawn", "v_anglePrevious", value); }
	}

	// m_iHideHUD
	[SchemaMember("CBasePlayerPawn", "m_iHideHUD")]
	public UInt32 HideHUD
	{
		get { return Schema.GetValueType<UInt32>(this.Handle, "CBasePlayerPawn", "m_iHideHUD"); }
		set { Schema.SetValueType<UInt32>(this.Handle, "CBasePlayerPawn", "m_iHideHUD", value); }
	}

	// m_skybox3d
	[SchemaMember("CBasePlayerPawn", "m_skybox3d")]
	public sky3dparams_t Skybox3d => Schema.GetDeclaredClass<sky3dparams_t>(this.Handle, "CBasePlayerPawn", "m_skybox3d");

	// m_fTimeLastHurt
	[SchemaMember("CBasePlayerPawn", "m_fTimeLastHurt")]
	public float TimeLastHurt
	{
		get { return Schema.GetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fTimeLastHurt"); }
		set { Schema.SetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fTimeLastHurt", value); }
	}

	// m_flDeathTime
	[SchemaMember("CBasePlayerPawn", "m_flDeathTime")]
	public float DeathTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CBasePlayerPawn", "m_flDeathTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CBasePlayerPawn", "m_flDeathTime", value); }
	}

	// m_fNextSuicideTime
	[SchemaMember("CBasePlayerPawn", "m_fNextSuicideTime")]
	public float NextSuicideTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fNextSuicideTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fNextSuicideTime", value); }
	}

	// m_fInitHUD
	[SchemaMember("CBasePlayerPawn", "m_fInitHUD")]
	public bool InitHUD
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CBasePlayerPawn", "m_fInitHUD"); }
		set { Schema.SetValueType<bool>(this.Handle, "CBasePlayerPawn", "m_fInitHUD", value); }
	}

	// m_pExpresser
	[SchemaMember("CBasePlayerPawn", "m_pExpresser")]
	public CAI_Expresser? Expresser => Schema.GetPointer<CAI_Expresser>(this.Handle, "CBasePlayerPawn", "m_pExpresser");

	// m_hController
	[SchemaMember("CBasePlayerPawn", "m_hController")]
	public CHandle<CBasePlayerController> Controller => Schema.GetDeclaredClass<CHandle<CBasePlayerController>>(this.Handle, "CBasePlayerPawn", "m_hController");

	// m_hDefaultController
	[SchemaMember("CBasePlayerPawn", "m_hDefaultController")]
	public CHandle<CBasePlayerController> DefaultController => Schema.GetDeclaredClass<CHandle<CBasePlayerController>>(this.Handle, "CBasePlayerPawn", "m_hDefaultController");

	// m_fHltvReplayDelay
	[SchemaMember("CBasePlayerPawn", "m_fHltvReplayDelay")]
	public float HltvReplayDelay
	{
		get { return Schema.GetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fHltvReplayDelay"); }
		set { Schema.SetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fHltvReplayDelay", value); }
	}

	// m_fHltvReplayEnd
	[SchemaMember("CBasePlayerPawn", "m_fHltvReplayEnd")]
	public float HltvReplayEnd
	{
		get { return Schema.GetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fHltvReplayEnd"); }
		set { Schema.SetValueType<float>(this.Handle, "CBasePlayerPawn", "m_fHltvReplayEnd", value); }
	}

	// m_iHltvReplayEntity
	[SchemaMember("CBasePlayerPawn", "m_iHltvReplayEntity")]
	public CEntityIndex HltvReplayEntity => Schema.GetDeclaredClass<CEntityIndex>(this.Handle, "CBasePlayerPawn", "m_iHltvReplayEntity");

	// m_sndOpvarLatchData
	[SchemaMember("CBasePlayerPawn", "m_sndOpvarLatchData")]
	public NetworkedVector<sndopvarlatchdata_t> SndOpvarLatchData => Schema.GetDeclaredClass<NetworkedVector<sndopvarlatchdata_t>>(this.Handle, "CBasePlayerPawn", "m_sndOpvarLatchData");

}
