// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CCollisionProperty : NativeObject
{
    public CCollisionProperty (IntPtr pointer) : base(pointer) {}

	// m_collisionAttribute
	[SchemaMember("CCollisionProperty", "m_collisionAttribute")]
	public virtual VPhysicsCollisionAttribute_t CollisionAttribute => Schema.GetDeclaredClass<VPhysicsCollisionAttribute_t>(this.Handle, "CCollisionProperty", "m_collisionAttribute");

	// m_vecMins
	[SchemaMember("CCollisionProperty", "m_vecMins")]
	public virtual Vector3 Mins
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecMins"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecMins", value); }
	}

	// m_vecMaxs
	[SchemaMember("CCollisionProperty", "m_vecMaxs")]
	public virtual Vector3 Maxs
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecMaxs"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecMaxs", value); }
	}

	// m_usSolidFlags
	[SchemaMember("CCollisionProperty", "m_usSolidFlags")]
	public virtual byte SolidFlags
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CCollisionProperty", "m_usSolidFlags"); }
		set { Schema.SetValueType<byte>(this.Handle, "CCollisionProperty", "m_usSolidFlags", value); }
	}

	// m_nSolidType
	[SchemaMember("CCollisionProperty", "m_nSolidType")]
	public virtual SolidType_t SolidType
	{
		get { return Schema.GetValueType<SolidType_t>(this.Handle, "CCollisionProperty", "m_nSolidType"); }
		set { Schema.SetValueType<SolidType_t>(this.Handle, "CCollisionProperty", "m_nSolidType", value); }
	}

	// m_triggerBloat
	[SchemaMember("CCollisionProperty", "m_triggerBloat")]
	public virtual byte TriggerBloat
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CCollisionProperty", "m_triggerBloat"); }
		set { Schema.SetValueType<byte>(this.Handle, "CCollisionProperty", "m_triggerBloat", value); }
	}

	// m_nSurroundType
	[SchemaMember("CCollisionProperty", "m_nSurroundType")]
	public virtual SurroundingBoundsType_t SurroundType
	{
		get { return Schema.GetValueType<SurroundingBoundsType_t>(this.Handle, "CCollisionProperty", "m_nSurroundType"); }
		set { Schema.SetValueType<SurroundingBoundsType_t>(this.Handle, "CCollisionProperty", "m_nSurroundType", value); }
	}

	// m_CollisionGroup
	[SchemaMember("CCollisionProperty", "m_CollisionGroup")]
	public virtual byte CollisionGroup
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CCollisionProperty", "m_CollisionGroup"); }
		set { Schema.SetValueType<byte>(this.Handle, "CCollisionProperty", "m_CollisionGroup", value); }
	}

	// m_nEnablePhysics
	[SchemaMember("CCollisionProperty", "m_nEnablePhysics")]
	public virtual byte EnablePhysics
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CCollisionProperty", "m_nEnablePhysics"); }
		set { Schema.SetValueType<byte>(this.Handle, "CCollisionProperty", "m_nEnablePhysics", value); }
	}

	// m_flBoundingRadius
	[SchemaMember("CCollisionProperty", "m_flBoundingRadius")]
	public virtual float BoundingRadius
	{
		get { return Schema.GetValueType<float>(this.Handle, "CCollisionProperty", "m_flBoundingRadius"); }
		set { Schema.SetValueType<float>(this.Handle, "CCollisionProperty", "m_flBoundingRadius", value); }
	}

	// m_vecSpecifiedSurroundingMins
	[SchemaMember("CCollisionProperty", "m_vecSpecifiedSurroundingMins")]
	public virtual Vector3 SpecifiedSurroundingMins
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSpecifiedSurroundingMins"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSpecifiedSurroundingMins", value); }
	}

	// m_vecSpecifiedSurroundingMaxs
	[SchemaMember("CCollisionProperty", "m_vecSpecifiedSurroundingMaxs")]
	public virtual Vector3 SpecifiedSurroundingMaxs
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSpecifiedSurroundingMaxs"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSpecifiedSurroundingMaxs", value); }
	}

	// m_vecSurroundingMaxs
	[SchemaMember("CCollisionProperty", "m_vecSurroundingMaxs")]
	public virtual Vector3 SurroundingMaxs
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSurroundingMaxs"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSurroundingMaxs", value); }
	}

	// m_vecSurroundingMins
	[SchemaMember("CCollisionProperty", "m_vecSurroundingMins")]
	public virtual Vector3 SurroundingMins
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSurroundingMins"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vecSurroundingMins", value); }
	}

	// m_vCapsuleCenter1
	[SchemaMember("CCollisionProperty", "m_vCapsuleCenter1")]
	public virtual Vector3 CapsuleCenter1
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vCapsuleCenter1"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vCapsuleCenter1", value); }
	}

	// m_vCapsuleCenter2
	[SchemaMember("CCollisionProperty", "m_vCapsuleCenter2")]
	public virtual Vector3 CapsuleCenter2
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vCapsuleCenter2"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CCollisionProperty", "m_vCapsuleCenter2", value); }
	}

	// m_flCapsuleRadius
	[SchemaMember("CCollisionProperty", "m_flCapsuleRadius")]
	public virtual float CapsuleRadius
	{
		get { return Schema.GetValueType<float>(this.Handle, "CCollisionProperty", "m_flCapsuleRadius"); }
		set { Schema.SetValueType<float>(this.Handle, "CCollisionProperty", "m_flCapsuleRadius", value); }
	}

	public virtual void CollisionAttributePropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_collisionAttribute");
	public virtual void MinsPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_vecMins");
	public virtual void MaxsPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_vecMaxs");
	public virtual void SolidFlagsPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_usSolidFlags");
	public virtual void SolidTypePropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_nSolidType");
	public virtual void TriggerBloatPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_triggerBloat");
	public virtual void SurroundTypePropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_nSurroundType");
	public virtual void CollisionGroupPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_CollisionGroup");
	public virtual void EnablePhysicsPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_nEnablePhysics");
	public virtual void SpecifiedSurroundingMinsPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_vecSpecifiedSurroundingMins");
	public virtual void SpecifiedSurroundingMaxsPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_vecSpecifiedSurroundingMaxs");
	public virtual void CapsuleCenter1PropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_vCapsuleCenter1");
	public virtual void CapsuleCenter2PropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_vCapsuleCenter2");
	public virtual void CapsuleRadiusPropertyChanged() => Utilities.SetStateChanged(this, "CCollisionProperty", "m_flCapsuleRadius");
}
