// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CCSPlayer_WeaponServices : CPlayer_WeaponServices
{
    public CCSPlayer_WeaponServices (IntPtr pointer) : base(pointer) {}

	// m_flNextAttack
	[SchemaMember("CCSPlayer_WeaponServices", "m_flNextAttack")]
	public ref float NextAttack => ref Schema.GetRef<float>(this.Handle, "CCSPlayer_WeaponServices", "m_flNextAttack");

	// m_bIsLookingAtWeapon
	[SchemaMember("CCSPlayer_WeaponServices", "m_bIsLookingAtWeapon")]
	public ref bool IsLookingAtWeapon => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bIsLookingAtWeapon");

	// m_bIsHoldingLookAtWeapon
	[SchemaMember("CCSPlayer_WeaponServices", "m_bIsHoldingLookAtWeapon")]
	public ref bool IsHoldingLookAtWeapon => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bIsHoldingLookAtWeapon");

	// m_hSavedWeapon
	[SchemaMember("CCSPlayer_WeaponServices", "m_hSavedWeapon")]
	public CHandle<CBasePlayerWeapon> SavedWeapon => Schema.GetDeclaredClass<CHandle<CBasePlayerWeapon>>(this.Handle, "CCSPlayer_WeaponServices", "m_hSavedWeapon");

	// m_nTimeToMelee
	[SchemaMember("CCSPlayer_WeaponServices", "m_nTimeToMelee")]
	public ref Int32 TimeToMelee => ref Schema.GetRef<Int32>(this.Handle, "CCSPlayer_WeaponServices", "m_nTimeToMelee");

	// m_nTimeToSecondary
	[SchemaMember("CCSPlayer_WeaponServices", "m_nTimeToSecondary")]
	public ref Int32 TimeToSecondary => ref Schema.GetRef<Int32>(this.Handle, "CCSPlayer_WeaponServices", "m_nTimeToSecondary");

	// m_nTimeToPrimary
	[SchemaMember("CCSPlayer_WeaponServices", "m_nTimeToPrimary")]
	public ref Int32 TimeToPrimary => ref Schema.GetRef<Int32>(this.Handle, "CCSPlayer_WeaponServices", "m_nTimeToPrimary");

	// m_nTimeToSniperRifle
	[SchemaMember("CCSPlayer_WeaponServices", "m_nTimeToSniperRifle")]
	public ref Int32 TimeToSniperRifle => ref Schema.GetRef<Int32>(this.Handle, "CCSPlayer_WeaponServices", "m_nTimeToSniperRifle");

	// m_bIsBeingGivenItem
	[SchemaMember("CCSPlayer_WeaponServices", "m_bIsBeingGivenItem")]
	public ref bool IsBeingGivenItem => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bIsBeingGivenItem");

	// m_bIsPickingUpItemWithUse
	[SchemaMember("CCSPlayer_WeaponServices", "m_bIsPickingUpItemWithUse")]
	public ref bool IsPickingUpItemWithUse => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bIsPickingUpItemWithUse");

	// m_bPickedUpWeapon
	[SchemaMember("CCSPlayer_WeaponServices", "m_bPickedUpWeapon")]
	public ref bool PickedUpWeapon => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bPickedUpWeapon");

	// m_bDisableAutoDeploy
	[SchemaMember("CCSPlayer_WeaponServices", "m_bDisableAutoDeploy")]
	public ref bool DisableAutoDeploy => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bDisableAutoDeploy");

	// m_bIsPickingUpGroundWeapon
	[SchemaMember("CCSPlayer_WeaponServices", "m_bIsPickingUpGroundWeapon")]
	public ref bool IsPickingUpGroundWeapon => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bIsPickingUpGroundWeapon");

	// m_networkAnimTiming
	[SchemaMember("CCSPlayer_WeaponServices", "m_networkAnimTiming")]
	public NetworkedVector<byte> NetworkAnimTiming => Schema.GetDeclaredClass<NetworkedVector<byte>>(this.Handle, "CCSPlayer_WeaponServices", "m_networkAnimTiming");

	// m_bBlockInspectUntilNextGraphUpdate
	[SchemaMember("CCSPlayer_WeaponServices", "m_bBlockInspectUntilNextGraphUpdate")]
	public ref bool BlockInspectUntilNextGraphUpdate => ref Schema.GetRef<bool>(this.Handle, "CCSPlayer_WeaponServices", "m_bBlockInspectUntilNextGraphUpdate");

}
