// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CDamageRecord : NativeObject
{
    public CDamageRecord (IntPtr pointer) : base(pointer) {}

	// m_PlayerDamager
	[SchemaMember("CDamageRecord", "m_PlayerDamager")]
	public CHandle<CCSPlayerPawn> PlayerDamager => Schema.GetDeclaredClass<CHandle<CCSPlayerPawn>>(this.Handle, "CDamageRecord", "m_PlayerDamager");

	// m_PlayerRecipient
	[SchemaMember("CDamageRecord", "m_PlayerRecipient")]
	public CHandle<CCSPlayerPawn> PlayerRecipient => Schema.GetDeclaredClass<CHandle<CCSPlayerPawn>>(this.Handle, "CDamageRecord", "m_PlayerRecipient");

	// m_hPlayerControllerDamager
	[SchemaMember("CDamageRecord", "m_hPlayerControllerDamager")]
	public CHandle<CCSPlayerController> PlayerControllerDamager => Schema.GetDeclaredClass<CHandle<CCSPlayerController>>(this.Handle, "CDamageRecord", "m_hPlayerControllerDamager");

	// m_hPlayerControllerRecipient
	[SchemaMember("CDamageRecord", "m_hPlayerControllerRecipient")]
	public CHandle<CCSPlayerController> PlayerControllerRecipient => Schema.GetDeclaredClass<CHandle<CCSPlayerController>>(this.Handle, "CDamageRecord", "m_hPlayerControllerRecipient");

	// m_szPlayerDamagerName
	[SchemaMember("CDamageRecord", "m_szPlayerDamagerName")]
	public string PlayerDamagerName
	{
		get { return Schema.GetUtf8String(this.Handle, "CDamageRecord", "m_szPlayerDamagerName"); }
		set { Schema.SetString(this.Handle, "CDamageRecord", "m_szPlayerDamagerName", value); }
	}

	// m_szPlayerRecipientName
	[SchemaMember("CDamageRecord", "m_szPlayerRecipientName")]
	public string PlayerRecipientName
	{
		get { return Schema.GetUtf8String(this.Handle, "CDamageRecord", "m_szPlayerRecipientName"); }
		set { Schema.SetString(this.Handle, "CDamageRecord", "m_szPlayerRecipientName", value); }
	}

	// m_DamagerXuid
	[SchemaMember("CDamageRecord", "m_DamagerXuid")]
	public UInt64 DamagerXuid
	{
		get { return Schema.GetValueType<UInt64>(this.Handle, "CDamageRecord", "m_DamagerXuid"); }
		set { Schema.SetValueType<UInt64>(this.Handle, "CDamageRecord", "m_DamagerXuid", value); }
	}

	// m_RecipientXuid
	[SchemaMember("CDamageRecord", "m_RecipientXuid")]
	public UInt64 RecipientXuid
	{
		get { return Schema.GetValueType<UInt64>(this.Handle, "CDamageRecord", "m_RecipientXuid"); }
		set { Schema.SetValueType<UInt64>(this.Handle, "CDamageRecord", "m_RecipientXuid", value); }
	}

	// m_flBulletsDamage
	[SchemaMember("CDamageRecord", "m_flBulletsDamage")]
	public float BulletsDamage
	{
		get { return Schema.GetValueType<float>(this.Handle, "CDamageRecord", "m_flBulletsDamage"); }
		set { Schema.SetValueType<float>(this.Handle, "CDamageRecord", "m_flBulletsDamage", value); }
	}

	// m_flDamage
	[SchemaMember("CDamageRecord", "m_flDamage")]
	public float Damage
	{
		get { return Schema.GetValueType<float>(this.Handle, "CDamageRecord", "m_flDamage"); }
		set { Schema.SetValueType<float>(this.Handle, "CDamageRecord", "m_flDamage", value); }
	}

	// m_flActualHealthRemoved
	[SchemaMember("CDamageRecord", "m_flActualHealthRemoved")]
	public float ActualHealthRemoved
	{
		get { return Schema.GetValueType<float>(this.Handle, "CDamageRecord", "m_flActualHealthRemoved"); }
		set { Schema.SetValueType<float>(this.Handle, "CDamageRecord", "m_flActualHealthRemoved", value); }
	}

	// m_iNumHits
	[SchemaMember("CDamageRecord", "m_iNumHits")]
	public Int32 NumHits
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CDamageRecord", "m_iNumHits"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CDamageRecord", "m_iNumHits", value); }
	}

	// m_iLastBulletUpdate
	[SchemaMember("CDamageRecord", "m_iLastBulletUpdate")]
	public Int32 LastBulletUpdate
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CDamageRecord", "m_iLastBulletUpdate"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CDamageRecord", "m_iLastBulletUpdate", value); }
	}

	// m_bIsOtherEnemy
	[SchemaMember("CDamageRecord", "m_bIsOtherEnemy")]
	public bool IsOtherEnemy
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CDamageRecord", "m_bIsOtherEnemy"); }
		set { Schema.SetValueType<bool>(this.Handle, "CDamageRecord", "m_bIsOtherEnemy", value); }
	}

	// m_killType
	[SchemaMember("CDamageRecord", "m_killType")]
	public EKillTypes_t KillType
	{
		get { return Schema.GetValueType<EKillTypes_t>(this.Handle, "CDamageRecord", "m_killType"); }
		set { Schema.SetValueType<EKillTypes_t>(this.Handle, "CDamageRecord", "m_killType", value); }
	}

}
