// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CEconItemAttribute : NativeObject
{
    public CEconItemAttribute (IntPtr pointer) : base(pointer) {}

	// m_iAttributeDefinitionIndex
	[SchemaMember("CEconItemAttribute", "m_iAttributeDefinitionIndex")]
	public UInt16 AttributeDefinitionIndex
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CEconItemAttribute", "m_iAttributeDefinitionIndex"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CEconItemAttribute", "m_iAttributeDefinitionIndex", value); }
	}

	// m_flValue
	[SchemaMember("CEconItemAttribute", "m_flValue")]
	public float Value
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEconItemAttribute", "m_flValue"); }
		set { Schema.SetValueType<float>(this.Handle, "CEconItemAttribute", "m_flValue", value); }
	}

	// m_flInitialValue
	[SchemaMember("CEconItemAttribute", "m_flInitialValue")]
	public float InitialValue
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEconItemAttribute", "m_flInitialValue"); }
		set { Schema.SetValueType<float>(this.Handle, "CEconItemAttribute", "m_flInitialValue", value); }
	}

	// m_nRefundableCurrency
	[SchemaMember("CEconItemAttribute", "m_nRefundableCurrency")]
	public Int32 RefundableCurrency
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CEconItemAttribute", "m_nRefundableCurrency"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CEconItemAttribute", "m_nRefundableCurrency", value); }
	}

	// m_bSetBonus
	[SchemaMember("CEconItemAttribute", "m_bSetBonus")]
	public bool SetBonus
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEconItemAttribute", "m_bSetBonus"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEconItemAttribute", "m_bSetBonus", value); }
	}

	public void AttributeDefinitionIndexPropertyChanged() => Utilities.SetStateChanged(this, "CEconItemAttribute", "m_iAttributeDefinitionIndex");
	public void ValuePropertyChanged() => Utilities.SetStateChanged(this, "CEconItemAttribute", "m_flValue");
	public void InitialValuePropertyChanged() => Utilities.SetStateChanged(this, "CEconItemAttribute", "m_flInitialValue");
	public void RefundableCurrencyPropertyChanged() => Utilities.SetStateChanged(this, "CEconItemAttribute", "m_nRefundableCurrency");
	public void SetBonusPropertyChanged() => Utilities.SetStateChanged(this, "CEconItemAttribute", "m_bSetBonus");
}
