// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CEnvInstructorHint : CPointEntity
{
    public CEnvInstructorHint (IntPtr pointer) : base(pointer) {}

	// m_iszName
	[SchemaMember("CEnvInstructorHint", "m_iszName")]
	public virtual string Name
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszName"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszName", value); }
	}

	// m_iszReplace_Key
	[SchemaMember("CEnvInstructorHint", "m_iszReplace_Key")]
	public virtual string Replace_Key
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszReplace_Key"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszReplace_Key", value); }
	}

	// m_iszHintTargetEntity
	[SchemaMember("CEnvInstructorHint", "m_iszHintTargetEntity")]
	public virtual string HintTargetEntity
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszHintTargetEntity"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszHintTargetEntity", value); }
	}

	// m_iTimeout
	[SchemaMember("CEnvInstructorHint", "m_iTimeout")]
	public virtual Int32 Timeout
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CEnvInstructorHint", "m_iTimeout"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CEnvInstructorHint", "m_iTimeout", value); }
	}

	// m_iDisplayLimit
	[SchemaMember("CEnvInstructorHint", "m_iDisplayLimit")]
	public virtual Int32 DisplayLimit
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CEnvInstructorHint", "m_iDisplayLimit"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CEnvInstructorHint", "m_iDisplayLimit", value); }
	}

	// m_iszIcon_Onscreen
	[SchemaMember("CEnvInstructorHint", "m_iszIcon_Onscreen")]
	public virtual string Icon_Onscreen
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszIcon_Onscreen"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszIcon_Onscreen", value); }
	}

	// m_iszIcon_Offscreen
	[SchemaMember("CEnvInstructorHint", "m_iszIcon_Offscreen")]
	public virtual string Icon_Offscreen
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszIcon_Offscreen"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszIcon_Offscreen", value); }
	}

	// m_iszCaption
	[SchemaMember("CEnvInstructorHint", "m_iszCaption")]
	public virtual string Caption
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszCaption"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszCaption", value); }
	}

	// m_iszActivatorCaption
	[SchemaMember("CEnvInstructorHint", "m_iszActivatorCaption")]
	public virtual string ActivatorCaption
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszActivatorCaption"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszActivatorCaption", value); }
	}

	// m_Color
	[SchemaMember("CEnvInstructorHint", "m_Color")]
	public virtual Color Color
	{
		get { return Schema.GetCustomMarshalledType<Color>(this.Handle, "CEnvInstructorHint", "m_Color"); }
		set { Schema.SetCustomMarshalledType<Color>(this.Handle, "CEnvInstructorHint", "m_Color", value); }
	}

	// m_fIconOffset
	[SchemaMember("CEnvInstructorHint", "m_fIconOffset")]
	public virtual float IconOffset
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvInstructorHint", "m_fIconOffset"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvInstructorHint", "m_fIconOffset", value); }
	}

	// m_fRange
	[SchemaMember("CEnvInstructorHint", "m_fRange")]
	public virtual float Range
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvInstructorHint", "m_fRange"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvInstructorHint", "m_fRange", value); }
	}

	// m_iPulseOption
	[SchemaMember("CEnvInstructorHint", "m_iPulseOption")]
	public virtual byte PulseOption
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CEnvInstructorHint", "m_iPulseOption"); }
		set { Schema.SetValueType<byte>(this.Handle, "CEnvInstructorHint", "m_iPulseOption", value); }
	}

	// m_iAlphaOption
	[SchemaMember("CEnvInstructorHint", "m_iAlphaOption")]
	public virtual byte AlphaOption
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CEnvInstructorHint", "m_iAlphaOption"); }
		set { Schema.SetValueType<byte>(this.Handle, "CEnvInstructorHint", "m_iAlphaOption", value); }
	}

	// m_iShakeOption
	[SchemaMember("CEnvInstructorHint", "m_iShakeOption")]
	public virtual byte ShakeOption
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CEnvInstructorHint", "m_iShakeOption"); }
		set { Schema.SetValueType<byte>(this.Handle, "CEnvInstructorHint", "m_iShakeOption", value); }
	}

	// m_bStatic
	[SchemaMember("CEnvInstructorHint", "m_bStatic")]
	public virtual bool Static
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bStatic"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bStatic", value); }
	}

	// m_bNoOffscreen
	[SchemaMember("CEnvInstructorHint", "m_bNoOffscreen")]
	public virtual bool NoOffscreen
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bNoOffscreen"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bNoOffscreen", value); }
	}

	// m_bForceCaption
	[SchemaMember("CEnvInstructorHint", "m_bForceCaption")]
	public virtual bool ForceCaption
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bForceCaption"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bForceCaption", value); }
	}

	// m_iInstanceType
	[SchemaMember("CEnvInstructorHint", "m_iInstanceType")]
	public virtual Int32 InstanceType
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CEnvInstructorHint", "m_iInstanceType"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CEnvInstructorHint", "m_iInstanceType", value); }
	}

	// m_bSuppressRest
	[SchemaMember("CEnvInstructorHint", "m_bSuppressRest")]
	public virtual bool SuppressRest
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bSuppressRest"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bSuppressRest", value); }
	}

	// m_iszBinding
	[SchemaMember("CEnvInstructorHint", "m_iszBinding")]
	public virtual string Binding
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvInstructorHint", "m_iszBinding"); }
		set { Schema.SetString(this.Handle, "CEnvInstructorHint", "m_iszBinding", value); }
	}

	// m_bAllowNoDrawTarget
	[SchemaMember("CEnvInstructorHint", "m_bAllowNoDrawTarget")]
	public virtual bool AllowNoDrawTarget
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bAllowNoDrawTarget"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bAllowNoDrawTarget", value); }
	}

	// m_bAutoStart
	[SchemaMember("CEnvInstructorHint", "m_bAutoStart")]
	public virtual bool AutoStart
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bAutoStart"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bAutoStart", value); }
	}

	// m_bLocalPlayerOnly
	[SchemaMember("CEnvInstructorHint", "m_bLocalPlayerOnly")]
	public virtual bool LocalPlayerOnly
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bLocalPlayerOnly"); }
		set { Schema.SetValueType<bool>(this.Handle, "CEnvInstructorHint", "m_bLocalPlayerOnly", value); }
	}

}
