// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CEnvWindShared : NativeObject
{
    public CEnvWindShared (IntPtr pointer) : base(pointer) {}

	// m_flStartTime
	[SchemaMember("CEnvWindShared", "m_flStartTime")]
	public virtual float StartTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvWindShared", "m_flStartTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvWindShared", "m_flStartTime", value); }
	}

	// m_iWindSeed
	[SchemaMember("CEnvWindShared", "m_iWindSeed")]
	public virtual UInt32 WindSeed
	{
		get { return Schema.GetValueType<UInt32>(this.Handle, "CEnvWindShared", "m_iWindSeed"); }
		set { Schema.SetValueType<UInt32>(this.Handle, "CEnvWindShared", "m_iWindSeed", value); }
	}

	// m_iMinWind
	[SchemaMember("CEnvWindShared", "m_iMinWind")]
	public virtual UInt16 MinWind
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMinWind"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMinWind", value); }
	}

	// m_iMaxWind
	[SchemaMember("CEnvWindShared", "m_iMaxWind")]
	public virtual UInt16 MaxWind
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMaxWind"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMaxWind", value); }
	}

	// m_windRadius
	[SchemaMember("CEnvWindShared", "m_windRadius")]
	public virtual Int32 WindRadius
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CEnvWindShared", "m_windRadius"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CEnvWindShared", "m_windRadius", value); }
	}

	// m_iMinGust
	[SchemaMember("CEnvWindShared", "m_iMinGust")]
	public virtual UInt16 MinGust
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMinGust"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMinGust", value); }
	}

	// m_iMaxGust
	[SchemaMember("CEnvWindShared", "m_iMaxGust")]
	public virtual UInt16 MaxGust
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMaxGust"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iMaxGust", value); }
	}

	// m_flMinGustDelay
	[SchemaMember("CEnvWindShared", "m_flMinGustDelay")]
	public virtual float MinGustDelay
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvWindShared", "m_flMinGustDelay"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvWindShared", "m_flMinGustDelay", value); }
	}

	// m_flMaxGustDelay
	[SchemaMember("CEnvWindShared", "m_flMaxGustDelay")]
	public virtual float MaxGustDelay
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvWindShared", "m_flMaxGustDelay"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvWindShared", "m_flMaxGustDelay", value); }
	}

	// m_flGustDuration
	[SchemaMember("CEnvWindShared", "m_flGustDuration")]
	public virtual float GustDuration
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvWindShared", "m_flGustDuration"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvWindShared", "m_flGustDuration", value); }
	}

	// m_iGustDirChange
	[SchemaMember("CEnvWindShared", "m_iGustDirChange")]
	public virtual UInt16 GustDirChange
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iGustDirChange"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iGustDirChange", value); }
	}

	// m_iInitialWindDir
	[SchemaMember("CEnvWindShared", "m_iInitialWindDir")]
	public virtual UInt16 InitialWindDir
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iInitialWindDir"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CEnvWindShared", "m_iInitialWindDir", value); }
	}

	// m_flInitialWindSpeed
	[SchemaMember("CEnvWindShared", "m_flInitialWindSpeed")]
	public virtual float InitialWindSpeed
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvWindShared", "m_flInitialWindSpeed"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvWindShared", "m_flInitialWindSpeed", value); }
	}

	// m_location
	[SchemaMember("CEnvWindShared", "m_location")]
	public virtual Vector3 Location
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CEnvWindShared", "m_location"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CEnvWindShared", "m_location", value); }
	}

	// m_OnGustStart
	[SchemaMember("CEnvWindShared", "m_OnGustStart")]
	public virtual CEntityIOOutput OnGustStart => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CEnvWindShared", "m_OnGustStart");

	// m_OnGustEnd
	[SchemaMember("CEnvWindShared", "m_OnGustEnd")]
	public virtual CEntityIOOutput OnGustEnd => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CEnvWindShared", "m_OnGustEnd");

	// m_hEntOwner
	[SchemaMember("CEnvWindShared", "m_hEntOwner")]
	public virtual CHandle<CBaseEntity> EntOwner
	{
		get { return Schema.GetValueType<CHandle<CBaseEntity>>(this.Handle, "CEnvWindShared", "m_hEntOwner"); }
		set { Schema.SetValueType<CHandle<CBaseEntity>>(this.Handle, "CEnvWindShared", "m_hEntOwner", value); }
	}

	public virtual void StartTimePropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_flStartTime");
	public virtual void WindSeedPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_iWindSeed");
	public virtual void MinWindPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_iMinWind");
	public virtual void MaxWindPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_iMaxWind");
	public virtual void WindRadiusPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_windRadius");
	public virtual void MinGustPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_iMinGust");
	public virtual void MaxGustPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_iMaxGust");
	public virtual void MinGustDelayPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_flMinGustDelay");
	public virtual void MaxGustDelayPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_flMaxGustDelay");
	public virtual void GustDurationPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_flGustDuration");
	public virtual void GustDirChangePropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_iGustDirChange");
	public virtual void InitialWindDirPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_iInitialWindDir");
	public virtual void InitialWindSpeedPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_flInitialWindSpeed");
	public virtual void LocationPropertyChanged() => Utilities.SetStateChanged(this, "CEnvWindShared", "m_location");
}
