// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CEnvShake : CPointEntity
{
    public CEnvShake (IntPtr pointer) : base(pointer) {}

	// m_limitToEntity
	[SchemaMember("CEnvShake", "m_limitToEntity")]
	public virtual string LimitToEntity
	{
		get { return Schema.GetUtf8String(this.Handle, "CEnvShake", "m_limitToEntity"); }
		set { Schema.SetString(this.Handle, "CEnvShake", "m_limitToEntity", value); }
	}

	// m_Amplitude
	[SchemaMember("CEnvShake", "m_Amplitude")]
	public virtual float Amplitude
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvShake", "m_Amplitude"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvShake", "m_Amplitude", value); }
	}

	// m_Frequency
	[SchemaMember("CEnvShake", "m_Frequency")]
	public virtual float Frequency
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvShake", "m_Frequency"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvShake", "m_Frequency", value); }
	}

	// m_Duration
	[SchemaMember("CEnvShake", "m_Duration")]
	public virtual float Duration
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvShake", "m_Duration"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvShake", "m_Duration", value); }
	}

	// m_Radius
	[SchemaMember("CEnvShake", "m_Radius")]
	public virtual float Radius
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvShake", "m_Radius"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvShake", "m_Radius", value); }
	}

	// m_stopTime
	[SchemaMember("CEnvShake", "m_stopTime")]
	public virtual float StopTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvShake", "m_stopTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvShake", "m_stopTime", value); }
	}

	// m_nextShake
	[SchemaMember("CEnvShake", "m_nextShake")]
	public virtual float NextShake
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvShake", "m_nextShake"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvShake", "m_nextShake", value); }
	}

	// m_currentAmp
	[SchemaMember("CEnvShake", "m_currentAmp")]
	public virtual float CurrentAmp
	{
		get { return Schema.GetValueType<float>(this.Handle, "CEnvShake", "m_currentAmp"); }
		set { Schema.SetValueType<float>(this.Handle, "CEnvShake", "m_currentAmp", value); }
	}

	// m_maxForce
	[SchemaMember("CEnvShake", "m_maxForce")]
	public virtual Vector3 MaxForce
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CEnvShake", "m_maxForce"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CEnvShake", "m_maxForce", value); }
	}

	// m_shakeCallback
	[SchemaMember("CEnvShake", "m_shakeCallback")]
	public virtual CPhysicsShake ShakeCallback => Schema.GetDeclaredClass<CPhysicsShake>(this.Handle, "CEnvShake", "m_shakeCallback");

}
