// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CFilterContext : CBaseFilter
{
    public CFilterContext (IntPtr pointer) : base(pointer) {}

	// m_iFilterContext
	[SchemaMember("CFilterContext", "m_iFilterContext")]
	public string FilterContext
	{
		get { return Schema.GetUtf8String(this.Handle, "CFilterContext", "m_iFilterContext"); }
		set { Schema.SetString(this.Handle, "CFilterContext", "m_iFilterContext", value); }
	}

}
