// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CFilterMassGreater : CBaseFilter
{
    public CFilterMassGreater (IntPtr pointer) : base(pointer) {}

	// m_fFilterMass
	[SchemaMember("CFilterMassGreater", "m_fFilterMass")]
	public virtual float FilterMass
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFilterMassGreater", "m_fFilterMass"); }
		set { Schema.SetValueType<float>(this.Handle, "CFilterMassGreater", "m_fFilterMass", value); }
	}

}
