// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CFilterMultiple : CBaseFilter
{
    public CFilterMultiple (IntPtr pointer) : base(pointer) {}

	// m_nFilterType
	[SchemaMember("CFilterMultiple", "m_nFilterType")]
	public filter_t FilterType
	{
		get { return Schema.GetValueType<filter_t>(this.Handle, "CFilterMultiple", "m_nFilterType"); }
		set { Schema.SetValueType<filter_t>(this.Handle, "CFilterMultiple", "m_nFilterType", value); }
	}

	// m_iFilterName
	[SchemaMember("CFilterMultiple", "m_iFilterName")]
	public Span<string> FilterName => Schema.GetFixedArray<string>(this.Handle, "CFilterMultiple", "m_iFilterName", 10);

	// m_hFilter
	[SchemaMember("CFilterMultiple", "m_hFilter")]
	public Span<CHandle<CBaseEntity>> Filter => Schema.GetFixedArray<CHandle<CBaseEntity>>(this.Handle, "CFilterMultiple", "m_hFilter", 10);

}
