// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CFlashbangProjectile : CBaseCSGrenadeProjectile
{
    public CFlashbangProjectile (IntPtr pointer) : base(pointer) {}

	// m_flTimeToDetonate
	[SchemaMember("CFlashbangProjectile", "m_flTimeToDetonate")]
	public virtual float TimeToDetonate
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFlashbangProjectile", "m_flTimeToDetonate"); }
		set { Schema.SetValueType<float>(this.Handle, "CFlashbangProjectile", "m_flTimeToDetonate", value); }
	}

	// m_numOpponentsHit
	[SchemaMember("CFlashbangProjectile", "m_numOpponentsHit")]
	public virtual byte NumOpponentsHit
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CFlashbangProjectile", "m_numOpponentsHit"); }
		set { Schema.SetValueType<byte>(this.Handle, "CFlashbangProjectile", "m_numOpponentsHit", value); }
	}

	// m_numTeammatesHit
	[SchemaMember("CFlashbangProjectile", "m_numTeammatesHit")]
	public virtual byte NumTeammatesHit
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CFlashbangProjectile", "m_numTeammatesHit"); }
		set { Schema.SetValueType<byte>(this.Handle, "CFlashbangProjectile", "m_numTeammatesHit", value); }
	}

}
