// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CFuncLadder : CBaseModelEntity
{
    public CFuncLadder (IntPtr pointer) : base(pointer) {}

	// m_vecLadderDir
	[SchemaMember("CFuncLadder", "m_vecLadderDir")]
	public virtual Vector3 LadderDir
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecLadderDir"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecLadderDir", value); }
	}

	// m_Dismounts
	[SchemaMember("CFuncLadder", "m_Dismounts")]
	public virtual NetworkedVector<CHandle<CInfoLadderDismount>> Dismounts => Schema.GetDeclaredClass<NetworkedVector<CHandle<CInfoLadderDismount>>>(this.Handle, "CFuncLadder", "m_Dismounts");

	// m_vecLocalTop
	[SchemaMember("CFuncLadder", "m_vecLocalTop")]
	public virtual Vector3 LocalTop
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecLocalTop"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecLocalTop", value); }
	}

	// m_vecPlayerMountPositionTop
	[SchemaMember("CFuncLadder", "m_vecPlayerMountPositionTop")]
	public virtual Vector3 PlayerMountPositionTop
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecPlayerMountPositionTop"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecPlayerMountPositionTop", value); }
	}

	// m_vecPlayerMountPositionBottom
	[SchemaMember("CFuncLadder", "m_vecPlayerMountPositionBottom")]
	public virtual Vector3 PlayerMountPositionBottom
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecPlayerMountPositionBottom"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CFuncLadder", "m_vecPlayerMountPositionBottom", value); }
	}

	// m_flAutoRideSpeed
	[SchemaMember("CFuncLadder", "m_flAutoRideSpeed")]
	public virtual float AutoRideSpeed
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFuncLadder", "m_flAutoRideSpeed"); }
		set { Schema.SetValueType<float>(this.Handle, "CFuncLadder", "m_flAutoRideSpeed", value); }
	}

	// m_bDisabled
	[SchemaMember("CFuncLadder", "m_bDisabled")]
	public virtual bool Disabled
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncLadder", "m_bDisabled"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncLadder", "m_bDisabled", value); }
	}

	// m_bFakeLadder
	[SchemaMember("CFuncLadder", "m_bFakeLadder")]
	public virtual bool FakeLadder
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncLadder", "m_bFakeLadder"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncLadder", "m_bFakeLadder", value); }
	}

	// m_bHasSlack
	[SchemaMember("CFuncLadder", "m_bHasSlack")]
	public virtual bool HasSlack
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncLadder", "m_bHasSlack"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncLadder", "m_bHasSlack", value); }
	}

	// m_surfacePropName
	[SchemaMember("CFuncLadder", "m_surfacePropName")]
	public virtual string SurfacePropName
	{
		get { return Schema.GetUtf8String(this.Handle, "CFuncLadder", "m_surfacePropName"); }
		set { Schema.SetString(this.Handle, "CFuncLadder", "m_surfacePropName", value); }
	}

	// m_OnPlayerGotOnLadder
	[SchemaMember("CFuncLadder", "m_OnPlayerGotOnLadder")]
	public virtual CEntityIOOutput OnPlayerGotOnLadder => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CFuncLadder", "m_OnPlayerGotOnLadder");

	// m_OnPlayerGotOffLadder
	[SchemaMember("CFuncLadder", "m_OnPlayerGotOffLadder")]
	public virtual CEntityIOOutput OnPlayerGotOffLadder => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CFuncLadder", "m_OnPlayerGotOffLadder");

	public virtual void LadderDirPropertyChanged() => Utilities.SetStateChanged(this, "CFuncLadder", "m_vecLadderDir");
	public virtual void PlayerMountPositionTopPropertyChanged() => Utilities.SetStateChanged(this, "CFuncLadder", "m_vecPlayerMountPositionTop");
	public virtual void PlayerMountPositionBottomPropertyChanged() => Utilities.SetStateChanged(this, "CFuncLadder", "m_vecPlayerMountPositionBottom");
	public virtual void AutoRideSpeedPropertyChanged() => Utilities.SetStateChanged(this, "CFuncLadder", "m_flAutoRideSpeed");
	public virtual void FakeLadderPropertyChanged() => Utilities.SetStateChanged(this, "CFuncLadder", "m_bFakeLadder");
}
