// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CFuncShatterglass : CBaseModelEntity
{
    public CFuncShatterglass (IntPtr pointer) : base(pointer) {}

	// m_matPanelTransform
	[SchemaMember("CFuncShatterglass", "m_matPanelTransform")]
	public matrix3x4_t MatPanelTransform => Schema.GetDeclaredClass<matrix3x4_t>(this.Handle, "CFuncShatterglass", "m_matPanelTransform");

	// m_matPanelTransformWsTemp
	[SchemaMember("CFuncShatterglass", "m_matPanelTransformWsTemp")]
	public matrix3x4_t MatPanelTransformWsTemp => Schema.GetDeclaredClass<matrix3x4_t>(this.Handle, "CFuncShatterglass", "m_matPanelTransformWsTemp");

	// m_vecShatterGlassShards
	[SchemaMember("CFuncShatterglass", "m_vecShatterGlassShards")]
	public NetworkedVector<UInt32> ShatterGlassShards => Schema.GetDeclaredClass<NetworkedVector<UInt32>>(this.Handle, "CFuncShatterglass", "m_vecShatterGlassShards");

	// m_PanelSize
	[SchemaMember("CFuncShatterglass", "m_PanelSize")]
	public Vector2D PanelSize => Schema.GetDeclaredClass<Vector2D>(this.Handle, "CFuncShatterglass", "m_PanelSize");

	// m_flLastShatterSoundEmitTime
	[SchemaMember("CFuncShatterglass", "m_flLastShatterSoundEmitTime")]
	public float LastShatterSoundEmitTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFuncShatterglass", "m_flLastShatterSoundEmitTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CFuncShatterglass", "m_flLastShatterSoundEmitTime", value); }
	}

	// m_flLastCleanupTime
	[SchemaMember("CFuncShatterglass", "m_flLastCleanupTime")]
	public float LastCleanupTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFuncShatterglass", "m_flLastCleanupTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CFuncShatterglass", "m_flLastCleanupTime", value); }
	}

	// m_flInitAtTime
	[SchemaMember("CFuncShatterglass", "m_flInitAtTime")]
	public float InitAtTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFuncShatterglass", "m_flInitAtTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CFuncShatterglass", "m_flInitAtTime", value); }
	}

	// m_flGlassThickness
	[SchemaMember("CFuncShatterglass", "m_flGlassThickness")]
	public float GlassThickness
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFuncShatterglass", "m_flGlassThickness"); }
		set { Schema.SetValueType<float>(this.Handle, "CFuncShatterglass", "m_flGlassThickness", value); }
	}

	// m_flSpawnInvulnerability
	[SchemaMember("CFuncShatterglass", "m_flSpawnInvulnerability")]
	public float SpawnInvulnerability
	{
		get { return Schema.GetValueType<float>(this.Handle, "CFuncShatterglass", "m_flSpawnInvulnerability"); }
		set { Schema.SetValueType<float>(this.Handle, "CFuncShatterglass", "m_flSpawnInvulnerability", value); }
	}

	// m_bBreakSilent
	[SchemaMember("CFuncShatterglass", "m_bBreakSilent")]
	public bool BreakSilent
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bBreakSilent"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bBreakSilent", value); }
	}

	// m_bBreakShardless
	[SchemaMember("CFuncShatterglass", "m_bBreakShardless")]
	public bool BreakShardless
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bBreakShardless"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bBreakShardless", value); }
	}

	// m_bBroken
	[SchemaMember("CFuncShatterglass", "m_bBroken")]
	public bool Broken
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bBroken"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bBroken", value); }
	}

	// m_bGlassNavIgnore
	[SchemaMember("CFuncShatterglass", "m_bGlassNavIgnore")]
	public bool GlassNavIgnore
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bGlassNavIgnore"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bGlassNavIgnore", value); }
	}

	// m_bGlassInFrame
	[SchemaMember("CFuncShatterglass", "m_bGlassInFrame")]
	public bool GlassInFrame
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bGlassInFrame"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bGlassInFrame", value); }
	}

	// m_bStartBroken
	[SchemaMember("CFuncShatterglass", "m_bStartBroken")]
	public bool StartBroken
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bStartBroken"); }
		set { Schema.SetValueType<bool>(this.Handle, "CFuncShatterglass", "m_bStartBroken", value); }
	}

	// m_iInitialDamageType
	[SchemaMember("CFuncShatterglass", "m_iInitialDamageType")]
	public byte InitialDamageType
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CFuncShatterglass", "m_iInitialDamageType"); }
		set { Schema.SetValueType<byte>(this.Handle, "CFuncShatterglass", "m_iInitialDamageType", value); }
	}

	// m_szDamagePositioningEntityName01
	[SchemaMember("CFuncShatterglass", "m_szDamagePositioningEntityName01")]
	public string DamagePositioningEntityName01
	{
		get { return Schema.GetUtf8String(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName01"); }
		set { Schema.SetString(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName01", value); }
	}

	// m_szDamagePositioningEntityName02
	[SchemaMember("CFuncShatterglass", "m_szDamagePositioningEntityName02")]
	public string DamagePositioningEntityName02
	{
		get { return Schema.GetUtf8String(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName02"); }
		set { Schema.SetString(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName02", value); }
	}

	// m_szDamagePositioningEntityName03
	[SchemaMember("CFuncShatterglass", "m_szDamagePositioningEntityName03")]
	public string DamagePositioningEntityName03
	{
		get { return Schema.GetUtf8String(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName03"); }
		set { Schema.SetString(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName03", value); }
	}

	// m_szDamagePositioningEntityName04
	[SchemaMember("CFuncShatterglass", "m_szDamagePositioningEntityName04")]
	public string DamagePositioningEntityName04
	{
		get { return Schema.GetUtf8String(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName04"); }
		set { Schema.SetString(this.Handle, "CFuncShatterglass", "m_szDamagePositioningEntityName04", value); }
	}

	// m_vInitialDamagePositions
	[SchemaMember("CFuncShatterglass", "m_vInitialDamagePositions")]
	public NetworkedVector<Vector3> InitialDamagePositions => Schema.GetDeclaredClass<NetworkedVector<Vector3>>(this.Handle, "CFuncShatterglass", "m_vInitialDamagePositions");

	// m_vExtraDamagePositions
	[SchemaMember("CFuncShatterglass", "m_vExtraDamagePositions")]
	public NetworkedVector<Vector3> ExtraDamagePositions => Schema.GetDeclaredClass<NetworkedVector<Vector3>>(this.Handle, "CFuncShatterglass", "m_vExtraDamagePositions");

	// m_vInitialPanelVertices
	[SchemaMember("CFuncShatterglass", "m_vInitialPanelVertices")]
	public NetworkedVector<Vector4D> InitialPanelVertices => Schema.GetDeclaredClass<NetworkedVector<Vector4D>>(this.Handle, "CFuncShatterglass", "m_vInitialPanelVertices");

	// m_OnBroken
	[SchemaMember("CFuncShatterglass", "m_OnBroken")]
	public CEntityIOOutput OnBroken => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CFuncShatterglass", "m_OnBroken");

	// m_iSurfaceType
	[SchemaMember("CFuncShatterglass", "m_iSurfaceType")]
	public byte SurfaceType
	{
		get { return Schema.GetValueType<byte>(this.Handle, "CFuncShatterglass", "m_iSurfaceType"); }
		set { Schema.SetValueType<byte>(this.Handle, "CFuncShatterglass", "m_iSurfaceType", value); }
	}

	// m_hMaterialDamageBase
	[SchemaMember("CFuncShatterglass", "m_hMaterialDamageBase")]
	public CStrongHandle<InfoForResourceTypeIMaterial2> MaterialDamageBase => Schema.GetDeclaredClass<CStrongHandle<InfoForResourceTypeIMaterial2>>(this.Handle, "CFuncShatterglass", "m_hMaterialDamageBase");

}
