// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CLightComponent : CEntityComponent
{
    public CLightComponent (IntPtr pointer) : base(pointer) {}

	// __m_pChainEntity
	[SchemaMember("CLightComponent", "__m_pChainEntity")]
	public virtual CNetworkVarChainer __m_pChainEntity => Schema.GetDeclaredClass<CNetworkVarChainer>(this.Handle, "CLightComponent", "__m_pChainEntity");

	// m_Color
	[SchemaMember("CLightComponent", "m_Color")]
	public virtual Color Color
	{
		get { return Schema.GetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_Color"); }
		set { Schema.SetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_Color", value); }
	}

	// m_SecondaryColor
	[SchemaMember("CLightComponent", "m_SecondaryColor")]
	public virtual Color SecondaryColor
	{
		get { return Schema.GetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_SecondaryColor"); }
		set { Schema.SetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_SecondaryColor", value); }
	}

	// m_flBrightness
	[SchemaMember("CLightComponent", "m_flBrightness")]
	public virtual float Brightness
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flBrightness"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flBrightness", value); }
	}

	// m_flBrightnessScale
	[SchemaMember("CLightComponent", "m_flBrightnessScale")]
	public virtual float BrightnessScale
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flBrightnessScale"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flBrightnessScale", value); }
	}

	// m_flBrightnessMult
	[SchemaMember("CLightComponent", "m_flBrightnessMult")]
	public virtual float BrightnessMult
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flBrightnessMult"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flBrightnessMult", value); }
	}

	// m_flRange
	[SchemaMember("CLightComponent", "m_flRange")]
	public virtual float Range
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flRange"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flRange", value); }
	}

	// m_flFalloff
	[SchemaMember("CLightComponent", "m_flFalloff")]
	public virtual float Falloff
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flFalloff"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flFalloff", value); }
	}

	// m_flAttenuation0
	[SchemaMember("CLightComponent", "m_flAttenuation0")]
	public virtual float Attenuation0
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flAttenuation0"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flAttenuation0", value); }
	}

	// m_flAttenuation1
	[SchemaMember("CLightComponent", "m_flAttenuation1")]
	public virtual float Attenuation1
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flAttenuation1"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flAttenuation1", value); }
	}

	// m_flAttenuation2
	[SchemaMember("CLightComponent", "m_flAttenuation2")]
	public virtual float Attenuation2
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flAttenuation2"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flAttenuation2", value); }
	}

	// m_flTheta
	[SchemaMember("CLightComponent", "m_flTheta")]
	public virtual float Theta
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flTheta"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flTheta", value); }
	}

	// m_flPhi
	[SchemaMember("CLightComponent", "m_flPhi")]
	public virtual float Phi
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flPhi"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flPhi", value); }
	}

	// m_hLightCookie
	[SchemaMember("CLightComponent", "m_hLightCookie")]
	public virtual CStrongHandle<InfoForResourceTypeCTextureBase> LightCookie => Schema.GetDeclaredClass<CStrongHandle<InfoForResourceTypeCTextureBase>>(this.Handle, "CLightComponent", "m_hLightCookie");

	// m_nCascades
	[SchemaMember("CLightComponent", "m_nCascades")]
	public virtual Int32 Cascades
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nCascades"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nCascades", value); }
	}

	// m_nCastShadows
	[SchemaMember("CLightComponent", "m_nCastShadows")]
	public virtual Int32 CastShadows
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nCastShadows"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nCastShadows", value); }
	}

	// m_nShadowWidth
	[SchemaMember("CLightComponent", "m_nShadowWidth")]
	public virtual Int32 ShadowWidth
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowWidth"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowWidth", value); }
	}

	// m_nShadowHeight
	[SchemaMember("CLightComponent", "m_nShadowHeight")]
	public virtual Int32 ShadowHeight
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowHeight"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowHeight", value); }
	}

	// m_bRenderDiffuse
	[SchemaMember("CLightComponent", "m_bRenderDiffuse")]
	public virtual bool RenderDiffuse
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bRenderDiffuse"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bRenderDiffuse", value); }
	}

	// m_nRenderSpecular
	[SchemaMember("CLightComponent", "m_nRenderSpecular")]
	public virtual Int32 RenderSpecular
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nRenderSpecular"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nRenderSpecular", value); }
	}

	// m_bRenderTransmissive
	[SchemaMember("CLightComponent", "m_bRenderTransmissive")]
	public virtual bool RenderTransmissive
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bRenderTransmissive"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bRenderTransmissive", value); }
	}

	// m_flOrthoLightWidth
	[SchemaMember("CLightComponent", "m_flOrthoLightWidth")]
	public virtual float OrthoLightWidth
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flOrthoLightWidth"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flOrthoLightWidth", value); }
	}

	// m_flOrthoLightHeight
	[SchemaMember("CLightComponent", "m_flOrthoLightHeight")]
	public virtual float OrthoLightHeight
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flOrthoLightHeight"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flOrthoLightHeight", value); }
	}

	// m_nStyle
	[SchemaMember("CLightComponent", "m_nStyle")]
	public virtual Int32 Style
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nStyle"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nStyle", value); }
	}

	// m_Pattern
	[SchemaMember("CLightComponent", "m_Pattern")]
	public virtual string Pattern
	{
		get { return Schema.GetUtf8String(this.Handle, "CLightComponent", "m_Pattern"); }
		set { Schema.SetString(this.Handle, "CLightComponent", "m_Pattern", value); }
	}

	// m_nCascadeRenderStaticObjects
	[SchemaMember("CLightComponent", "m_nCascadeRenderStaticObjects")]
	public virtual Int32 CascadeRenderStaticObjects
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nCascadeRenderStaticObjects"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nCascadeRenderStaticObjects", value); }
	}

	// m_flShadowCascadeCrossFade
	[SchemaMember("CLightComponent", "m_flShadowCascadeCrossFade")]
	public virtual float ShadowCascadeCrossFade
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeCrossFade"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeCrossFade", value); }
	}

	// m_flShadowCascadeDistanceFade
	[SchemaMember("CLightComponent", "m_flShadowCascadeDistanceFade")]
	public virtual float ShadowCascadeDistanceFade
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistanceFade"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistanceFade", value); }
	}

	// m_flShadowCascadeDistance0
	[SchemaMember("CLightComponent", "m_flShadowCascadeDistance0")]
	public virtual float ShadowCascadeDistance0
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance0"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance0", value); }
	}

	// m_flShadowCascadeDistance1
	[SchemaMember("CLightComponent", "m_flShadowCascadeDistance1")]
	public virtual float ShadowCascadeDistance1
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance1"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance1", value); }
	}

	// m_flShadowCascadeDistance2
	[SchemaMember("CLightComponent", "m_flShadowCascadeDistance2")]
	public virtual float ShadowCascadeDistance2
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance2"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance2", value); }
	}

	// m_flShadowCascadeDistance3
	[SchemaMember("CLightComponent", "m_flShadowCascadeDistance3")]
	public virtual float ShadowCascadeDistance3
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance3"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowCascadeDistance3", value); }
	}

	// m_nShadowCascadeResolution0
	[SchemaMember("CLightComponent", "m_nShadowCascadeResolution0")]
	public virtual Int32 ShadowCascadeResolution0
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution0"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution0", value); }
	}

	// m_nShadowCascadeResolution1
	[SchemaMember("CLightComponent", "m_nShadowCascadeResolution1")]
	public virtual Int32 ShadowCascadeResolution1
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution1"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution1", value); }
	}

	// m_nShadowCascadeResolution2
	[SchemaMember("CLightComponent", "m_nShadowCascadeResolution2")]
	public virtual Int32 ShadowCascadeResolution2
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution2"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution2", value); }
	}

	// m_nShadowCascadeResolution3
	[SchemaMember("CLightComponent", "m_nShadowCascadeResolution3")]
	public virtual Int32 ShadowCascadeResolution3
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution3"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowCascadeResolution3", value); }
	}

	// m_bUsesBakedShadowing
	[SchemaMember("CLightComponent", "m_bUsesBakedShadowing")]
	public virtual bool UsesBakedShadowing
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bUsesBakedShadowing"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bUsesBakedShadowing", value); }
	}

	// m_nShadowPriority
	[SchemaMember("CLightComponent", "m_nShadowPriority")]
	public virtual Int32 ShadowPriority
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowPriority"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nShadowPriority", value); }
	}

	// m_nBakedShadowIndex
	[SchemaMember("CLightComponent", "m_nBakedShadowIndex")]
	public virtual Int32 BakedShadowIndex
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nBakedShadowIndex"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nBakedShadowIndex", value); }
	}

	// m_nLightPathUniqueId
	[SchemaMember("CLightComponent", "m_nLightPathUniqueId")]
	public virtual Int32 LightPathUniqueId
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nLightPathUniqueId"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nLightPathUniqueId", value); }
	}

	// m_nLightMapUniqueId
	[SchemaMember("CLightComponent", "m_nLightMapUniqueId")]
	public virtual Int32 LightMapUniqueId
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nLightMapUniqueId"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nLightMapUniqueId", value); }
	}

	// m_bRenderToCubemaps
	[SchemaMember("CLightComponent", "m_bRenderToCubemaps")]
	public virtual bool RenderToCubemaps
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bRenderToCubemaps"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bRenderToCubemaps", value); }
	}

	// m_bAllowSSTGeneration
	[SchemaMember("CLightComponent", "m_bAllowSSTGeneration")]
	public virtual bool AllowSSTGeneration
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bAllowSSTGeneration"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bAllowSSTGeneration", value); }
	}

	// m_nDirectLight
	[SchemaMember("CLightComponent", "m_nDirectLight")]
	public virtual Int32 DirectLight
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nDirectLight"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nDirectLight", value); }
	}

	// m_nIndirectLight
	[SchemaMember("CLightComponent", "m_nIndirectLight")]
	public virtual Int32 IndirectLight
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nIndirectLight"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nIndirectLight", value); }
	}

	// m_flFadeMinDist
	[SchemaMember("CLightComponent", "m_flFadeMinDist")]
	public virtual float FadeMinDist
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flFadeMinDist"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flFadeMinDist", value); }
	}

	// m_flFadeMaxDist
	[SchemaMember("CLightComponent", "m_flFadeMaxDist")]
	public virtual float FadeMaxDist
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flFadeMaxDist"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flFadeMaxDist", value); }
	}

	// m_flShadowFadeMinDist
	[SchemaMember("CLightComponent", "m_flShadowFadeMinDist")]
	public virtual float ShadowFadeMinDist
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowFadeMinDist"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowFadeMinDist", value); }
	}

	// m_flShadowFadeMaxDist
	[SchemaMember("CLightComponent", "m_flShadowFadeMaxDist")]
	public virtual float ShadowFadeMaxDist
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flShadowFadeMaxDist"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flShadowFadeMaxDist", value); }
	}

	// m_bEnabled
	[SchemaMember("CLightComponent", "m_bEnabled")]
	public virtual bool Enabled
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bEnabled"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bEnabled", value); }
	}

	// m_bFlicker
	[SchemaMember("CLightComponent", "m_bFlicker")]
	public virtual bool Flicker
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bFlicker"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bFlicker", value); }
	}

	// m_bPrecomputedFieldsValid
	[SchemaMember("CLightComponent", "m_bPrecomputedFieldsValid")]
	public virtual bool PrecomputedFieldsValid
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bPrecomputedFieldsValid"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bPrecomputedFieldsValid", value); }
	}

	// m_vPrecomputedBoundsMins
	[SchemaMember("CLightComponent", "m_vPrecomputedBoundsMins")]
	public virtual Vector3 PrecomputedBoundsMins
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedBoundsMins"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedBoundsMins", value); }
	}

	// m_vPrecomputedBoundsMaxs
	[SchemaMember("CLightComponent", "m_vPrecomputedBoundsMaxs")]
	public virtual Vector3 PrecomputedBoundsMaxs
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedBoundsMaxs"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedBoundsMaxs", value); }
	}

	// m_vPrecomputedOBBOrigin
	[SchemaMember("CLightComponent", "m_vPrecomputedOBBOrigin")]
	public virtual Vector3 PrecomputedOBBOrigin
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedOBBOrigin"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedOBBOrigin", value); }
	}

	// m_vPrecomputedOBBAngles
	[SchemaMember("CLightComponent", "m_vPrecomputedOBBAngles")]
	public virtual QAngle PrecomputedOBBAngles
	{
		get { return Schema.GetValueType<QAngle>(this.Handle, "CLightComponent", "m_vPrecomputedOBBAngles"); }
		set { Schema.SetValueType<QAngle>(this.Handle, "CLightComponent", "m_vPrecomputedOBBAngles", value); }
	}

	// m_vPrecomputedOBBExtent
	[SchemaMember("CLightComponent", "m_vPrecomputedOBBExtent")]
	public virtual Vector3 PrecomputedOBBExtent
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedOBBExtent"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CLightComponent", "m_vPrecomputedOBBExtent", value); }
	}

	// m_flPrecomputedMaxRange
	[SchemaMember("CLightComponent", "m_flPrecomputedMaxRange")]
	public virtual float PrecomputedMaxRange
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flPrecomputedMaxRange"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flPrecomputedMaxRange", value); }
	}

	// m_nFogLightingMode
	[SchemaMember("CLightComponent", "m_nFogLightingMode")]
	public virtual Int32 FogLightingMode
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CLightComponent", "m_nFogLightingMode"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CLightComponent", "m_nFogLightingMode", value); }
	}

	// m_flFogContributionStength
	[SchemaMember("CLightComponent", "m_flFogContributionStength")]
	public virtual float FogContributionStength
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flFogContributionStength"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flFogContributionStength", value); }
	}

	// m_flNearClipPlane
	[SchemaMember("CLightComponent", "m_flNearClipPlane")]
	public virtual float NearClipPlane
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flNearClipPlane"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flNearClipPlane", value); }
	}

	// m_SkyColor
	[SchemaMember("CLightComponent", "m_SkyColor")]
	public virtual Color SkyColor
	{
		get { return Schema.GetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_SkyColor"); }
		set { Schema.SetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_SkyColor", value); }
	}

	// m_flSkyIntensity
	[SchemaMember("CLightComponent", "m_flSkyIntensity")]
	public virtual float SkyIntensity
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flSkyIntensity"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flSkyIntensity", value); }
	}

	// m_SkyAmbientBounce
	[SchemaMember("CLightComponent", "m_SkyAmbientBounce")]
	public virtual Color SkyAmbientBounce
	{
		get { return Schema.GetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_SkyAmbientBounce"); }
		set { Schema.SetCustomMarshalledType<Color>(this.Handle, "CLightComponent", "m_SkyAmbientBounce", value); }
	}

	// m_bUseSecondaryColor
	[SchemaMember("CLightComponent", "m_bUseSecondaryColor")]
	public virtual bool UseSecondaryColor
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bUseSecondaryColor"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bUseSecondaryColor", value); }
	}

	// m_bMixedShadows
	[SchemaMember("CLightComponent", "m_bMixedShadows")]
	public virtual bool MixedShadows
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bMixedShadows"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bMixedShadows", value); }
	}

	// m_flLightStyleStartTime
	[SchemaMember("CLightComponent", "m_flLightStyleStartTime")]
	public virtual float LightStyleStartTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flLightStyleStartTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flLightStyleStartTime", value); }
	}

	// m_flCapsuleLength
	[SchemaMember("CLightComponent", "m_flCapsuleLength")]
	public virtual float CapsuleLength
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flCapsuleLength"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flCapsuleLength", value); }
	}

	// m_flMinRoughness
	[SchemaMember("CLightComponent", "m_flMinRoughness")]
	public virtual float MinRoughness
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLightComponent", "m_flMinRoughness"); }
		set { Schema.SetValueType<float>(this.Handle, "CLightComponent", "m_flMinRoughness", value); }
	}

	// m_bPvsModifyEntity
	[SchemaMember("CLightComponent", "m_bPvsModifyEntity")]
	public virtual bool PvsModifyEntity
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CLightComponent", "m_bPvsModifyEntity"); }
		set { Schema.SetValueType<bool>(this.Handle, "CLightComponent", "m_bPvsModifyEntity", value); }
	}

	public virtual void ColorPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_Color");
	public virtual void SecondaryColorPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_SecondaryColor");
	public virtual void BrightnessPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flBrightness");
	public virtual void BrightnessScalePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flBrightnessScale");
	public virtual void BrightnessMultPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flBrightnessMult");
	public virtual void RangePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flRange");
	public virtual void FalloffPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flFalloff");
	public virtual void Attenuation0PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flAttenuation0");
	public virtual void Attenuation1PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flAttenuation1");
	public virtual void Attenuation2PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flAttenuation2");
	public virtual void ThetaPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flTheta");
	public virtual void PhiPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flPhi");
	public virtual void LightCookiePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_hLightCookie");
	public virtual void CascadesPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nCascades");
	public virtual void CastShadowsPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nCastShadows");
	public virtual void ShadowWidthPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nShadowWidth");
	public virtual void ShadowHeightPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nShadowHeight");
	public virtual void RenderDiffusePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bRenderDiffuse");
	public virtual void RenderSpecularPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nRenderSpecular");
	public virtual void RenderTransmissivePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bRenderTransmissive");
	public virtual void OrthoLightWidthPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flOrthoLightWidth");
	public virtual void OrthoLightHeightPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flOrthoLightHeight");
	public virtual void StylePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nStyle");
	public virtual void PatternPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_Pattern");
	public virtual void CascadeRenderStaticObjectsPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nCascadeRenderStaticObjects");
	public virtual void ShadowCascadeCrossFadePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowCascadeCrossFade");
	public virtual void ShadowCascadeDistanceFadePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowCascadeDistanceFade");
	public virtual void ShadowCascadeDistance0PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowCascadeDistance0");
	public virtual void ShadowCascadeDistance1PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowCascadeDistance1");
	public virtual void ShadowCascadeDistance2PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowCascadeDistance2");
	public virtual void ShadowCascadeDistance3PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowCascadeDistance3");
	public virtual void ShadowCascadeResolution0PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nShadowCascadeResolution0");
	public virtual void ShadowCascadeResolution1PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nShadowCascadeResolution1");
	public virtual void ShadowCascadeResolution2PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nShadowCascadeResolution2");
	public virtual void ShadowCascadeResolution3PropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nShadowCascadeResolution3");
	public virtual void UsesBakedShadowingPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bUsesBakedShadowing");
	public virtual void ShadowPriorityPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nShadowPriority");
	public virtual void BakedShadowIndexPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nBakedShadowIndex");
	public virtual void LightPathUniqueIdPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nLightPathUniqueId");
	public virtual void LightMapUniqueIdPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nLightMapUniqueId");
	public virtual void RenderToCubemapsPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bRenderToCubemaps");
	public virtual void AllowSSTGenerationPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bAllowSSTGeneration");
	public virtual void DirectLightPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nDirectLight");
	public virtual void IndirectLightPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nIndirectLight");
	public virtual void FadeMinDistPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flFadeMinDist");
	public virtual void FadeMaxDistPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flFadeMaxDist");
	public virtual void ShadowFadeMinDistPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowFadeMinDist");
	public virtual void ShadowFadeMaxDistPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flShadowFadeMaxDist");
	public virtual void EnabledPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bEnabled");
	public virtual void FlickerPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bFlicker");
	public virtual void PrecomputedFieldsValidPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bPrecomputedFieldsValid");
	public virtual void PrecomputedBoundsMinsPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_vPrecomputedBoundsMins");
	public virtual void PrecomputedBoundsMaxsPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_vPrecomputedBoundsMaxs");
	public virtual void PrecomputedOBBOriginPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_vPrecomputedOBBOrigin");
	public virtual void PrecomputedOBBAnglesPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_vPrecomputedOBBAngles");
	public virtual void PrecomputedOBBExtentPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_vPrecomputedOBBExtent");
	public virtual void PrecomputedMaxRangePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flPrecomputedMaxRange");
	public virtual void FogLightingModePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_nFogLightingMode");
	public virtual void FogContributionStengthPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flFogContributionStength");
	public virtual void NearClipPlanePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flNearClipPlane");
	public virtual void SkyColorPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_SkyColor");
	public virtual void SkyIntensityPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flSkyIntensity");
	public virtual void SkyAmbientBouncePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_SkyAmbientBounce");
	public virtual void UseSecondaryColorPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bUseSecondaryColor");
	public virtual void MixedShadowsPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_bMixedShadows");
	public virtual void LightStyleStartTimePropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flLightStyleStartTime");
	public virtual void CapsuleLengthPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flCapsuleLength");
	public virtual void MinRoughnessPropertyChanged() => Utilities.SetStateChanged(this, "CLightComponent", "m_flMinRoughness");
}
