// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CLogicEventListener : CLogicalEntity
{
    public CLogicEventListener (IntPtr pointer) : base(pointer) {}

	// m_strEventName
	[SchemaMember("CLogicEventListener", "m_strEventName")]
	public string StrEventName
	{
		get { return Schema.GetUtf8String(this.Handle, "CLogicEventListener", "m_strEventName"); }
		set { Schema.SetString(this.Handle, "CLogicEventListener", "m_strEventName", value); }
	}

	// m_bIsEnabled
	[SchemaMember("CLogicEventListener", "m_bIsEnabled")]
	public ref bool IsEnabled => ref Schema.GetRef<bool>(this.Handle, "CLogicEventListener", "m_bIsEnabled");

	// m_nTeam
	[SchemaMember("CLogicEventListener", "m_nTeam")]
	public ref Int32 Team => ref Schema.GetRef<Int32>(this.Handle, "CLogicEventListener", "m_nTeam");

	// m_OnEventFired
	[SchemaMember("CLogicEventListener", "m_OnEventFired")]
	public CEntityIOOutput OnEventFired => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CLogicEventListener", "m_OnEventFired");

}
