// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CLogicDistanceCheck : CLogicalEntity
{
    public CLogicDistanceCheck (IntPtr pointer) : base(pointer) {}

	// m_iszEntityA
	[SchemaMember("CLogicDistanceCheck", "m_iszEntityA")]
	public virtual string EntityA
	{
		get { return Schema.GetUtf8String(this.Handle, "CLogicDistanceCheck", "m_iszEntityA"); }
		set { Schema.SetString(this.Handle, "CLogicDistanceCheck", "m_iszEntityA", value); }
	}

	// m_iszEntityB
	[SchemaMember("CLogicDistanceCheck", "m_iszEntityB")]
	public virtual string EntityB
	{
		get { return Schema.GetUtf8String(this.Handle, "CLogicDistanceCheck", "m_iszEntityB"); }
		set { Schema.SetString(this.Handle, "CLogicDistanceCheck", "m_iszEntityB", value); }
	}

	// m_flZone1Distance
	[SchemaMember("CLogicDistanceCheck", "m_flZone1Distance")]
	public virtual float Zone1Distance
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLogicDistanceCheck", "m_flZone1Distance"); }
		set { Schema.SetValueType<float>(this.Handle, "CLogicDistanceCheck", "m_flZone1Distance", value); }
	}

	// m_flZone2Distance
	[SchemaMember("CLogicDistanceCheck", "m_flZone2Distance")]
	public virtual float Zone2Distance
	{
		get { return Schema.GetValueType<float>(this.Handle, "CLogicDistanceCheck", "m_flZone2Distance"); }
		set { Schema.SetValueType<float>(this.Handle, "CLogicDistanceCheck", "m_flZone2Distance", value); }
	}

	// m_InZone1
	[SchemaMember("CLogicDistanceCheck", "m_InZone1")]
	public virtual CEntityIOOutput InZone1 => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CLogicDistanceCheck", "m_InZone1");

	// m_InZone2
	[SchemaMember("CLogicDistanceCheck", "m_InZone2")]
	public virtual CEntityIOOutput InZone2 => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CLogicDistanceCheck", "m_InZone2");

	// m_InZone3
	[SchemaMember("CLogicDistanceCheck", "m_InZone3")]
	public virtual CEntityIOOutput InZone3 => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CLogicDistanceCheck", "m_InZone3");

}
