// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CMessageEntity : CPointEntity
{
    public CMessageEntity (IntPtr pointer) : base(pointer) {}

	// m_radius
	[SchemaMember("CMessageEntity", "m_radius")]
	public virtual Int32 Radius
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CMessageEntity", "m_radius"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CMessageEntity", "m_radius", value); }
	}

	// m_messageText
	[SchemaMember("CMessageEntity", "m_messageText")]
	public virtual string MessageText
	{
		get { return Schema.GetUtf8String(this.Handle, "CMessageEntity", "m_messageText"); }
		set { Schema.SetString(this.Handle, "CMessageEntity", "m_messageText", value); }
	}

	// m_drawText
	[SchemaMember("CMessageEntity", "m_drawText")]
	public virtual bool DrawText
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CMessageEntity", "m_drawText"); }
		set { Schema.SetValueType<bool>(this.Handle, "CMessageEntity", "m_drawText", value); }
	}

	// m_bDeveloperOnly
	[SchemaMember("CMessageEntity", "m_bDeveloperOnly")]
	public virtual bool DeveloperOnly
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CMessageEntity", "m_bDeveloperOnly"); }
		set { Schema.SetValueType<bool>(this.Handle, "CMessageEntity", "m_bDeveloperOnly", value); }
	}

	// m_bEnabled
	[SchemaMember("CMessageEntity", "m_bEnabled")]
	public virtual bool Enabled
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CMessageEntity", "m_bEnabled"); }
		set { Schema.SetValueType<bool>(this.Handle, "CMessageEntity", "m_bEnabled", value); }
	}

}
