// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CNavLinkAreaEntity : CPointEntity
{
    public CNavLinkAreaEntity (IntPtr pointer) : base(pointer) {}

	// m_flWidth
	[SchemaMember("CNavLinkAreaEntity", "m_flWidth")]
	public virtual float Width
	{
		get { return Schema.GetValueType<float>(this.Handle, "CNavLinkAreaEntity", "m_flWidth"); }
		set { Schema.SetValueType<float>(this.Handle, "CNavLinkAreaEntity", "m_flWidth", value); }
	}

	// m_vLocatorOffset
	[SchemaMember("CNavLinkAreaEntity", "m_vLocatorOffset")]
	public virtual Vector3 LocatorOffset
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CNavLinkAreaEntity", "m_vLocatorOffset"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CNavLinkAreaEntity", "m_vLocatorOffset", value); }
	}

	// m_qLocatorAnglesOffset
	[SchemaMember("CNavLinkAreaEntity", "m_qLocatorAnglesOffset")]
	public virtual QAngle LocatorAnglesOffset
	{
		get { return Schema.GetValueType<QAngle>(this.Handle, "CNavLinkAreaEntity", "m_qLocatorAnglesOffset"); }
		set { Schema.SetValueType<QAngle>(this.Handle, "CNavLinkAreaEntity", "m_qLocatorAnglesOffset", value); }
	}

	// m_strMovementForward
	[SchemaMember("CNavLinkAreaEntity", "m_strMovementForward")]
	public virtual string StrMovementForward
	{
		get { return Schema.GetUtf8String(this.Handle, "CNavLinkAreaEntity", "m_strMovementForward"); }
		set { Schema.SetString(this.Handle, "CNavLinkAreaEntity", "m_strMovementForward", value); }
	}

	// m_strMovementReverse
	[SchemaMember("CNavLinkAreaEntity", "m_strMovementReverse")]
	public virtual string StrMovementReverse
	{
		get { return Schema.GetUtf8String(this.Handle, "CNavLinkAreaEntity", "m_strMovementReverse"); }
		set { Schema.SetString(this.Handle, "CNavLinkAreaEntity", "m_strMovementReverse", value); }
	}

	// m_bEnabled
	[SchemaMember("CNavLinkAreaEntity", "m_bEnabled")]
	public virtual bool Enabled
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CNavLinkAreaEntity", "m_bEnabled"); }
		set { Schema.SetValueType<bool>(this.Handle, "CNavLinkAreaEntity", "m_bEnabled", value); }
	}

	// m_bAllowCrossMovableConnections
	[SchemaMember("CNavLinkAreaEntity", "m_bAllowCrossMovableConnections")]
	public virtual bool AllowCrossMovableConnections
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CNavLinkAreaEntity", "m_bAllowCrossMovableConnections"); }
		set { Schema.SetValueType<bool>(this.Handle, "CNavLinkAreaEntity", "m_bAllowCrossMovableConnections", value); }
	}

	// m_strFilterName
	[SchemaMember("CNavLinkAreaEntity", "m_strFilterName")]
	public virtual string StrFilterName
	{
		get { return Schema.GetUtf8String(this.Handle, "CNavLinkAreaEntity", "m_strFilterName"); }
		set { Schema.SetString(this.Handle, "CNavLinkAreaEntity", "m_strFilterName", value); }
	}

	// m_hFilter
	[SchemaMember("CNavLinkAreaEntity", "m_hFilter")]
	public virtual CHandle<CBaseFilter> Filter
	{
		get { return Schema.GetValueType<CHandle<CBaseFilter>>(this.Handle, "CNavLinkAreaEntity", "m_hFilter"); }
		set { Schema.SetValueType<CHandle<CBaseFilter>>(this.Handle, "CNavLinkAreaEntity", "m_hFilter", value); }
	}

	// m_OnNavLinkStart
	[SchemaMember("CNavLinkAreaEntity", "m_OnNavLinkStart")]
	public virtual CEntityIOOutput OnNavLinkStart => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CNavLinkAreaEntity", "m_OnNavLinkStart");

	// m_OnNavLinkFinish
	[SchemaMember("CNavLinkAreaEntity", "m_OnNavLinkFinish")]
	public virtual CEntityIOOutput OnNavLinkFinish => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CNavLinkAreaEntity", "m_OnNavLinkFinish");

	// m_bIsTerminus
	[SchemaMember("CNavLinkAreaEntity", "m_bIsTerminus")]
	public virtual bool IsTerminus
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CNavLinkAreaEntity", "m_bIsTerminus"); }
		set { Schema.SetValueType<bool>(this.Handle, "CNavLinkAreaEntity", "m_bIsTerminus", value); }
	}

	// m_nSplits
	[SchemaMember("CNavLinkAreaEntity", "m_nSplits")]
	public virtual Int32 Splits
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CNavLinkAreaEntity", "m_nSplits"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CNavLinkAreaEntity", "m_nSplits", value); }
	}

}
