// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CNavLinkAnimgraphVar : NativeObject
{
    public CNavLinkAnimgraphVar (IntPtr pointer) : base(pointer) {}

	// m_sAnimGraphNavlinkType
	[SchemaMember("CNavLinkAnimgraphVar", "m_sAnimGraphNavlinkType")]
	public virtual string AnimGraphNavlinkType
	{
		get { return Schema.GetUtf8String(this.Handle, "CNavLinkAnimgraphVar", "m_sAnimGraphNavlinkType"); }
		set { Schema.SetString(this.Handle, "CNavLinkAnimgraphVar", "m_sAnimGraphNavlinkType", value); }
	}

	// m_unAlignmentDegrees
	[SchemaMember("CNavLinkAnimgraphVar", "m_unAlignmentDegrees")]
	public virtual UInt32 AlignmentDegrees
	{
		get { return Schema.GetValueType<UInt32>(this.Handle, "CNavLinkAnimgraphVar", "m_unAlignmentDegrees"); }
		set { Schema.SetValueType<UInt32>(this.Handle, "CNavLinkAnimgraphVar", "m_unAlignmentDegrees", value); }
	}

}
