// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CNetworkOriginCellCoordQuantizedVector : NativeObject
{
    public CNetworkOriginCellCoordQuantizedVector (IntPtr pointer) : base(pointer) {}

	// m_cellX
	[SchemaMember("CNetworkOriginCellCoordQuantizedVector", "m_cellX")]
	public virtual UInt16 CellX
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_cellX"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_cellX", value); }
	}

	// m_cellY
	[SchemaMember("CNetworkOriginCellCoordQuantizedVector", "m_cellY")]
	public virtual UInt16 CellY
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_cellY"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_cellY", value); }
	}

	// m_cellZ
	[SchemaMember("CNetworkOriginCellCoordQuantizedVector", "m_cellZ")]
	public virtual UInt16 CellZ
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_cellZ"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_cellZ", value); }
	}

	// m_nOutsideWorld
	[SchemaMember("CNetworkOriginCellCoordQuantizedVector", "m_nOutsideWorld")]
	public virtual UInt16 OutsideWorld
	{
		get { return Schema.GetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_nOutsideWorld"); }
		set { Schema.SetValueType<UInt16>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_nOutsideWorld", value); }
	}

	// m_vecX
	[SchemaMember("CNetworkOriginCellCoordQuantizedVector", "m_vecX")]
	public virtual float X
	{
		get { return Schema.GetValueType<float>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_vecX"); }
		set { Schema.SetValueType<float>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_vecX", value); }
	}

	// m_vecY
	[SchemaMember("CNetworkOriginCellCoordQuantizedVector", "m_vecY")]
	public virtual float Y
	{
		get { return Schema.GetValueType<float>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_vecY"); }
		set { Schema.SetValueType<float>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_vecY", value); }
	}

	// m_vecZ
	[SchemaMember("CNetworkOriginCellCoordQuantizedVector", "m_vecZ")]
	public virtual float Z
	{
		get { return Schema.GetValueType<float>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_vecZ"); }
		set { Schema.SetValueType<float>(this.Handle, "CNetworkOriginCellCoordQuantizedVector", "m_vecZ", value); }
	}

	public virtual void CellXPropertyChanged() => Utilities.SetStateChanged(this, "CNetworkOriginCellCoordQuantizedVector", "m_cellX");
	public virtual void CellYPropertyChanged() => Utilities.SetStateChanged(this, "CNetworkOriginCellCoordQuantizedVector", "m_cellY");
	public virtual void CellZPropertyChanged() => Utilities.SetStateChanged(this, "CNetworkOriginCellCoordQuantizedVector", "m_cellZ");
	public virtual void OutsideWorldPropertyChanged() => Utilities.SetStateChanged(this, "CNetworkOriginCellCoordQuantizedVector", "m_nOutsideWorld");
	public virtual void XPropertyChanged() => Utilities.SetStateChanged(this, "CNetworkOriginCellCoordQuantizedVector", "m_vecX");
	public virtual void YPropertyChanged() => Utilities.SetStateChanged(this, "CNetworkOriginCellCoordQuantizedVector", "m_vecY");
	public virtual void ZPropertyChanged() => Utilities.SetStateChanged(this, "CNetworkOriginCellCoordQuantizedVector", "m_vecZ");
}
