// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CParticleSystem : CBaseModelEntity
{
    public CParticleSystem (IntPtr pointer) : base(pointer) {}

	// m_szSnapshotFileName
	[SchemaMember("CParticleSystem", "m_szSnapshotFileName")]
	public virtual string SnapshotFileName
	{
		get { return Schema.GetString(this.Handle, "CParticleSystem", "m_szSnapshotFileName"); }
		set { Schema.SetStringBytes(this.Handle, "CParticleSystem", "m_szSnapshotFileName", value, 512); }
	}

	// m_bActive
	[SchemaMember("CParticleSystem", "m_bActive")]
	public virtual bool Active
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CParticleSystem", "m_bActive"); }
		set { Schema.SetValueType<bool>(this.Handle, "CParticleSystem", "m_bActive", value); }
	}

	// m_bFrozen
	[SchemaMember("CParticleSystem", "m_bFrozen")]
	public virtual bool Frozen
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CParticleSystem", "m_bFrozen"); }
		set { Schema.SetValueType<bool>(this.Handle, "CParticleSystem", "m_bFrozen", value); }
	}

	// m_flFreezeTransitionDuration
	[SchemaMember("CParticleSystem", "m_flFreezeTransitionDuration")]
	public virtual float FreezeTransitionDuration
	{
		get { return Schema.GetValueType<float>(this.Handle, "CParticleSystem", "m_flFreezeTransitionDuration"); }
		set { Schema.SetValueType<float>(this.Handle, "CParticleSystem", "m_flFreezeTransitionDuration", value); }
	}

	// m_nStopType
	[SchemaMember("CParticleSystem", "m_nStopType")]
	public virtual Int32 StopType
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CParticleSystem", "m_nStopType"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CParticleSystem", "m_nStopType", value); }
	}

	// m_bAnimateDuringGameplayPause
	[SchemaMember("CParticleSystem", "m_bAnimateDuringGameplayPause")]
	public virtual bool AnimateDuringGameplayPause
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CParticleSystem", "m_bAnimateDuringGameplayPause"); }
		set { Schema.SetValueType<bool>(this.Handle, "CParticleSystem", "m_bAnimateDuringGameplayPause", value); }
	}

	// m_iEffectIndex
	[SchemaMember("CParticleSystem", "m_iEffectIndex")]
	public virtual CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> EffectIndex => Schema.GetDeclaredClass<CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>>(this.Handle, "CParticleSystem", "m_iEffectIndex");

	// m_flStartTime
	[SchemaMember("CParticleSystem", "m_flStartTime")]
	public virtual float StartTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CParticleSystem", "m_flStartTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CParticleSystem", "m_flStartTime", value); }
	}

	// m_flPreSimTime
	[SchemaMember("CParticleSystem", "m_flPreSimTime")]
	public virtual float PreSimTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CParticleSystem", "m_flPreSimTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CParticleSystem", "m_flPreSimTime", value); }
	}

	// m_vServerControlPoints
	[SchemaMember("CParticleSystem", "m_vServerControlPoints")]
	public virtual Span<Vector3> ServerControlPoints => Schema.GetFixedArray<Vector3>(this.Handle, "CParticleSystem", "m_vServerControlPoints", 4);

	// m_iServerControlPointAssignments
	[SchemaMember("CParticleSystem", "m_iServerControlPointAssignments")]
	public virtual Span<byte> ServerControlPointAssignments => Schema.GetFixedArray<byte>(this.Handle, "CParticleSystem", "m_iServerControlPointAssignments", 4);

	// m_hControlPointEnts
	[SchemaMember("CParticleSystem", "m_hControlPointEnts")]
	public virtual Span<CHandle<CBaseEntity>> ControlPointEnts => Schema.GetFixedArray<CHandle<CBaseEntity>>(this.Handle, "CParticleSystem", "m_hControlPointEnts", 64);

	// m_bNoSave
	[SchemaMember("CParticleSystem", "m_bNoSave")]
	public virtual bool NoSave
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CParticleSystem", "m_bNoSave"); }
		set { Schema.SetValueType<bool>(this.Handle, "CParticleSystem", "m_bNoSave", value); }
	}

	// m_bNoFreeze
	[SchemaMember("CParticleSystem", "m_bNoFreeze")]
	public virtual bool NoFreeze
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CParticleSystem", "m_bNoFreeze"); }
		set { Schema.SetValueType<bool>(this.Handle, "CParticleSystem", "m_bNoFreeze", value); }
	}

	// m_bNoRamp
	[SchemaMember("CParticleSystem", "m_bNoRamp")]
	public virtual bool NoRamp
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CParticleSystem", "m_bNoRamp"); }
		set { Schema.SetValueType<bool>(this.Handle, "CParticleSystem", "m_bNoRamp", value); }
	}

	// m_bStartActive
	[SchemaMember("CParticleSystem", "m_bStartActive")]
	public virtual bool StartActive
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CParticleSystem", "m_bStartActive"); }
		set { Schema.SetValueType<bool>(this.Handle, "CParticleSystem", "m_bStartActive", value); }
	}

	// m_iszEffectName
	[SchemaMember("CParticleSystem", "m_iszEffectName")]
	public virtual string EffectName
	{
		get { return Schema.GetUtf8String(this.Handle, "CParticleSystem", "m_iszEffectName"); }
		set { Schema.SetString(this.Handle, "CParticleSystem", "m_iszEffectName", value); }
	}

	// m_iszControlPointNames
	[SchemaMember("CParticleSystem", "m_iszControlPointNames")]
	public virtual Span<string> ControlPointNames => Schema.GetFixedArray<string>(this.Handle, "CParticleSystem", "m_iszControlPointNames", 64);

	// m_nDataCP
	[SchemaMember("CParticleSystem", "m_nDataCP")]
	public virtual Int32 DataCP
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CParticleSystem", "m_nDataCP"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CParticleSystem", "m_nDataCP", value); }
	}

	// m_vecDataCPValue
	[SchemaMember("CParticleSystem", "m_vecDataCPValue")]
	public virtual Vector3 DataCPValue
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CParticleSystem", "m_vecDataCPValue"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CParticleSystem", "m_vecDataCPValue", value); }
	}

	// m_nTintCP
	[SchemaMember("CParticleSystem", "m_nTintCP")]
	public virtual Int32 TintCP
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CParticleSystem", "m_nTintCP"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CParticleSystem", "m_nTintCP", value); }
	}

	// m_clrTint
	[SchemaMember("CParticleSystem", "m_clrTint")]
	public virtual Color Tint
	{
		get { return Schema.GetCustomMarshalledType<Color>(this.Handle, "CParticleSystem", "m_clrTint"); }
		set { Schema.SetCustomMarshalledType<Color>(this.Handle, "CParticleSystem", "m_clrTint", value); }
	}

	public virtual void SnapshotFileNamePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_szSnapshotFileName");
	public virtual void ActivePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_bActive");
	public virtual void FrozenPropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_bFrozen");
	public virtual void FreezeTransitionDurationPropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_flFreezeTransitionDuration");
	public virtual void StopTypePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_nStopType");
	public virtual void AnimateDuringGameplayPausePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_bAnimateDuringGameplayPause");
	public virtual void EffectIndexPropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_iEffectIndex");
	public virtual void StartTimePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_flStartTime");
	public virtual void PreSimTimePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_flPreSimTime");
	public virtual void ServerControlPointsPropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_vServerControlPoints");
	public virtual void ServerControlPointAssignmentsPropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_iServerControlPointAssignments");
	public virtual void ControlPointEntsPropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_hControlPointEnts");
	public virtual void NoSavePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_bNoSave");
	public virtual void NoFreezePropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_bNoFreeze");
	public virtual void NoRampPropertyChanged() => Utilities.SetStateChanged(this, "CParticleSystem", "m_bNoRamp");
}
