// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CPathParticleRope : CBaseEntity
{
    public CPathParticleRope (IntPtr pointer) : base(pointer) {}

	// m_bStartActive
	[SchemaMember("CPathParticleRope", "m_bStartActive")]
	public bool StartActive
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CPathParticleRope", "m_bStartActive"); }
		set { Schema.SetValueType<bool>(this.Handle, "CPathParticleRope", "m_bStartActive", value); }
	}

	// m_flMaxSimulationTime
	[SchemaMember("CPathParticleRope", "m_flMaxSimulationTime")]
	public float MaxSimulationTime
	{
		get { return Schema.GetValueType<float>(this.Handle, "CPathParticleRope", "m_flMaxSimulationTime"); }
		set { Schema.SetValueType<float>(this.Handle, "CPathParticleRope", "m_flMaxSimulationTime", value); }
	}

	// m_iszEffectName
	[SchemaMember("CPathParticleRope", "m_iszEffectName")]
	public string EffectName
	{
		get { return Schema.GetUtf8String(this.Handle, "CPathParticleRope", "m_iszEffectName"); }
		set { Schema.SetString(this.Handle, "CPathParticleRope", "m_iszEffectName", value); }
	}

	// m_PathNodes_Name
	[SchemaMember("CPathParticleRope", "m_PathNodes_Name")]
	public NetworkedVector<string> PathNodes_Name => Schema.GetDeclaredClass<NetworkedVector<string>>(this.Handle, "CPathParticleRope", "m_PathNodes_Name");

	// m_flParticleSpacing
	[SchemaMember("CPathParticleRope", "m_flParticleSpacing")]
	public float ParticleSpacing
	{
		get { return Schema.GetValueType<float>(this.Handle, "CPathParticleRope", "m_flParticleSpacing"); }
		set { Schema.SetValueType<float>(this.Handle, "CPathParticleRope", "m_flParticleSpacing", value); }
	}

	// m_flSlack
	[SchemaMember("CPathParticleRope", "m_flSlack")]
	public float Slack
	{
		get { return Schema.GetValueType<float>(this.Handle, "CPathParticleRope", "m_flSlack"); }
		set { Schema.SetValueType<float>(this.Handle, "CPathParticleRope", "m_flSlack", value); }
	}

	// m_flRadius
	[SchemaMember("CPathParticleRope", "m_flRadius")]
	public float Radius
	{
		get { return Schema.GetValueType<float>(this.Handle, "CPathParticleRope", "m_flRadius"); }
		set { Schema.SetValueType<float>(this.Handle, "CPathParticleRope", "m_flRadius", value); }
	}

	// m_ColorTint
	[SchemaMember("CPathParticleRope", "m_ColorTint")]
	public Color ColorTint
	{
		get { return Schema.GetCustomMarshalledType<Color>(this.Handle, "CPathParticleRope", "m_ColorTint"); }
		set { Schema.SetCustomMarshalledType<Color>(this.Handle, "CPathParticleRope", "m_ColorTint", value); }
	}

	// m_nEffectState
	[SchemaMember("CPathParticleRope", "m_nEffectState")]
	public Int32 EffectState
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CPathParticleRope", "m_nEffectState"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CPathParticleRope", "m_nEffectState", value); }
	}

	// m_iEffectIndex
	[SchemaMember("CPathParticleRope", "m_iEffectIndex")]
	public CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> EffectIndex => Schema.GetDeclaredClass<CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>>(this.Handle, "CPathParticleRope", "m_iEffectIndex");

	// m_PathNodes_Position
	[SchemaMember("CPathParticleRope", "m_PathNodes_Position")]
	public NetworkedVector<Vector3> PathNodes_Position => Schema.GetDeclaredClass<NetworkedVector<Vector3>>(this.Handle, "CPathParticleRope", "m_PathNodes_Position");

	// m_PathNodes_TangentIn
	[SchemaMember("CPathParticleRope", "m_PathNodes_TangentIn")]
	public NetworkedVector<Vector3> PathNodes_TangentIn => Schema.GetDeclaredClass<NetworkedVector<Vector3>>(this.Handle, "CPathParticleRope", "m_PathNodes_TangentIn");

	// m_PathNodes_TangentOut
	[SchemaMember("CPathParticleRope", "m_PathNodes_TangentOut")]
	public NetworkedVector<Vector3> PathNodes_TangentOut => Schema.GetDeclaredClass<NetworkedVector<Vector3>>(this.Handle, "CPathParticleRope", "m_PathNodes_TangentOut");

	// m_PathNodes_Color
	[SchemaMember("CPathParticleRope", "m_PathNodes_Color")]
	public NetworkedVector<Vector3> PathNodes_Color => Schema.GetDeclaredClass<NetworkedVector<Vector3>>(this.Handle, "CPathParticleRope", "m_PathNodes_Color");

	// m_PathNodes_PinEnabled
	[SchemaMember("CPathParticleRope", "m_PathNodes_PinEnabled")]
	public NetworkedVector<bool> PathNodes_PinEnabled => Schema.GetDeclaredClass<NetworkedVector<bool>>(this.Handle, "CPathParticleRope", "m_PathNodes_PinEnabled");

	// m_PathNodes_RadiusScale
	[SchemaMember("CPathParticleRope", "m_PathNodes_RadiusScale")]
	public NetworkedVector<float> PathNodes_RadiusScale => Schema.GetDeclaredClass<NetworkedVector<float>>(this.Handle, "CPathParticleRope", "m_PathNodes_RadiusScale");

}
