// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CPathMover : CBaseEntity
{
    public CPathMover (IntPtr pointer) : base(pointer) {}

	// m_vecPathNodes
	[SchemaMember("CPathMover", "m_vecPathNodes")]
	public NetworkedVector<CHandle<CMoverPathNode>> PathNodes => Schema.GetDeclaredClass<NetworkedVector<CHandle<CMoverPathNode>>>(this.Handle, "CPathMover", "m_vecPathNodes");

	// m_flPathLength
	[SchemaMember("CPathMover", "m_flPathLength")]
	public ref float PathLength => ref Schema.GetRef<float>(this.Handle, "CPathMover", "m_flPathLength");

	// m_bClosedLoop
	[SchemaMember("CPathMover", "m_bClosedLoop")]
	public ref bool ClosedLoop => ref Schema.GetRef<bool>(this.Handle, "CPathMover", "m_bClosedLoop");

}
