// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CPlayerPing : CBaseEntity
{
    public CPlayerPing (IntPtr pointer) : base(pointer) {}

	// m_hPlayer
	[SchemaMember("CPlayerPing", "m_hPlayer")]
	public CHandle<CCSPlayerPawn> Player => Schema.GetDeclaredClass<CHandle<CCSPlayerPawn>>(this.Handle, "CPlayerPing", "m_hPlayer");

	// m_hPingedEntity
	[SchemaMember("CPlayerPing", "m_hPingedEntity")]
	public CHandle<CBaseEntity> PingedEntity => Schema.GetDeclaredClass<CHandle<CBaseEntity>>(this.Handle, "CPlayerPing", "m_hPingedEntity");

	// m_iType
	[SchemaMember("CPlayerPing", "m_iType")]
	public ref Int32 Type => ref Schema.GetRef<Int32>(this.Handle, "CPlayerPing", "m_iType");

	// m_bUrgent
	[SchemaMember("CPlayerPing", "m_bUrgent")]
	public ref bool Urgent => ref Schema.GetRef<bool>(this.Handle, "CPlayerPing", "m_bUrgent");

	// m_szPlaceName
	[SchemaMember("CPlayerPing", "m_szPlaceName")]
	public string PlaceName
	{
		get { return Schema.GetString(this.Handle, "CPlayerPing", "m_szPlaceName"); }
		set { Schema.SetStringBytes(this.Handle, "CPlayerPing", "m_szPlaceName", value, 18); }
	}

}
