// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;
using CounterStrikeSharp.API.Natives;
using CounterStrikeSharp.API.Natives.Structs;

namespace CounterStrikeSharp.API.Core;

public partial class CRetakeGameRules : NativeObject
{
    public CRetakeGameRules (IntPtr pointer) : base(pointer) {}

	// m_nMatchSeed
	[SchemaMember("CRetakeGameRules", "m_nMatchSeed")]
	public virtual Int32 MatchSeed
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CRetakeGameRules", "m_nMatchSeed"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CRetakeGameRules", "m_nMatchSeed", value); }
	}

	// m_bBlockersPresent
	[SchemaMember("CRetakeGameRules", "m_bBlockersPresent")]
	public virtual bool BlockersPresent
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CRetakeGameRules", "m_bBlockersPresent"); }
		set { Schema.SetValueType<bool>(this.Handle, "CRetakeGameRules", "m_bBlockersPresent", value); }
	}

	// m_bRoundInProgress
	[SchemaMember("CRetakeGameRules", "m_bRoundInProgress")]
	public virtual bool RoundInProgress
	{
		get { return Schema.GetValueType<bool>(this.Handle, "CRetakeGameRules", "m_bRoundInProgress"); }
		set { Schema.SetValueType<bool>(this.Handle, "CRetakeGameRules", "m_bRoundInProgress", value); }
	}

	// m_iFirstSecondHalfRound
	[SchemaMember("CRetakeGameRules", "m_iFirstSecondHalfRound")]
	public virtual Int32 FirstSecondHalfRound
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CRetakeGameRules", "m_iFirstSecondHalfRound"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CRetakeGameRules", "m_iFirstSecondHalfRound", value); }
	}

	// m_iBombSite
	[SchemaMember("CRetakeGameRules", "m_iBombSite")]
	public virtual Int32 BombSite
	{
		get { return Schema.GetValueType<Int32>(this.Handle, "CRetakeGameRules", "m_iBombSite"); }
		set { Schema.SetValueType<Int32>(this.Handle, "CRetakeGameRules", "m_iBombSite", value); }
	}

	// m_hBombPlanter
	[SchemaMember("CRetakeGameRules", "m_hBombPlanter")]
	public virtual CHandle<CCSPlayerPawn> BombPlanter
	{
		get { return Schema.GetValueType<CHandle<CCSPlayerPawn>>(this.Handle, "CRetakeGameRules", "m_hBombPlanter"); }
		set { Schema.SetValueType<CHandle<CCSPlayerPawn>>(this.Handle, "CRetakeGameRules", "m_hBombPlanter", value); }
	}

	public virtual void MatchSeedPropertyChanged() => Utilities.SetStateChanged(this, "CRetakeGameRules", "m_nMatchSeed");
	public virtual void BlockersPresentPropertyChanged() => Utilities.SetStateChanged(this, "CRetakeGameRules", "m_bBlockersPresent");
	public virtual void RoundInProgressPropertyChanged() => Utilities.SetStateChanged(this, "CRetakeGameRules", "m_bRoundInProgress");
	public virtual void FirstSecondHalfRoundPropertyChanged() => Utilities.SetStateChanged(this, "CRetakeGameRules", "m_iFirstSecondHalfRound");
	public virtual void BombSitePropertyChanged() => Utilities.SetStateChanged(this, "CRetakeGameRules", "m_iBombSite");
	public virtual void BombPlanterPropertyChanged() => Utilities.SetStateChanged(this, "CRetakeGameRules", "m_hBombPlanter");
}
