// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CSensorGrenadeProjectile : CBaseCSGrenadeProjectile
{
    public CSensorGrenadeProjectile (IntPtr pointer) : base(pointer) {}

	// m_fExpireTime
	[SchemaMember("CSensorGrenadeProjectile", "m_fExpireTime")]
	public ref float ExpireTime => ref Schema.GetRef<float>(this.Handle, "CSensorGrenadeProjectile", "m_fExpireTime");

	// m_fNextDetectPlayerSound
	[SchemaMember("CSensorGrenadeProjectile", "m_fNextDetectPlayerSound")]
	public ref float NextDetectPlayerSound => ref Schema.GetRef<float>(this.Handle, "CSensorGrenadeProjectile", "m_fNextDetectPlayerSound");

	// m_hDisplayGrenade
	[SchemaMember("CSensorGrenadeProjectile", "m_hDisplayGrenade")]
	public CHandle<CBaseEntity> DisplayGrenade => Schema.GetDeclaredClass<CHandle<CBaseEntity>>(this.Handle, "CSensorGrenadeProjectile", "m_hDisplayGrenade");

}
