// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CSoundEventOBBEntity : CSoundEventEntity
{
    public CSoundEventOBBEntity (IntPtr pointer) : base(pointer) {}

	// m_vMins
	[SchemaMember("CSoundEventOBBEntity", "m_vMins")]
	public Vector3 Mins
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CSoundEventOBBEntity", "m_vMins"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CSoundEventOBBEntity", "m_vMins", value); }
	}

	// m_vMaxs
	[SchemaMember("CSoundEventOBBEntity", "m_vMaxs")]
	public Vector3 Maxs
	{
		get { return Schema.GetValueType<Vector3>(this.Handle, "CSoundEventOBBEntity", "m_vMaxs"); }
		set { Schema.SetValueType<Vector3>(this.Handle, "CSoundEventOBBEntity", "m_vMaxs", value); }
	}

	public void MinsPropertyChanged() => Utilities.SetStateChanged(this, "CSoundEventOBBEntity", "m_vMins");
	public void MaxsPropertyChanged() => Utilities.SetStateChanged(this, "CSoundEventOBBEntity", "m_vMaxs");
}
