// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CSoundEventPathCornerEntity : CSoundEventEntity
{
    public CSoundEventPathCornerEntity (IntPtr pointer) : base(pointer) {}

	// m_iszPathCorner
	[SchemaMember("CSoundEventPathCornerEntity", "m_iszPathCorner")]
	public string PathCorner
	{
		get { return Schema.GetUtf8String(this.Handle, "CSoundEventPathCornerEntity", "m_iszPathCorner"); }
		set { Schema.SetString(this.Handle, "CSoundEventPathCornerEntity", "m_iszPathCorner", value); }
	}

	// m_iCountMax
	[SchemaMember("CSoundEventPathCornerEntity", "m_iCountMax")]
	public ref Int32 CountMax => ref Schema.GetRef<Int32>(this.Handle, "CSoundEventPathCornerEntity", "m_iCountMax");

	// m_flDistanceMax
	[SchemaMember("CSoundEventPathCornerEntity", "m_flDistanceMax")]
	public ref float DistanceMax => ref Schema.GetRef<float>(this.Handle, "CSoundEventPathCornerEntity", "m_flDistanceMax");

	// m_flDistMaxSqr
	[SchemaMember("CSoundEventPathCornerEntity", "m_flDistMaxSqr")]
	public ref float DistMaxSqr => ref Schema.GetRef<float>(this.Handle, "CSoundEventPathCornerEntity", "m_flDistMaxSqr");

	// m_flDotProductMax
	[SchemaMember("CSoundEventPathCornerEntity", "m_flDotProductMax")]
	public ref float DotProductMax => ref Schema.GetRef<float>(this.Handle, "CSoundEventPathCornerEntity", "m_flDotProductMax");

	// m_bPlaying
	[SchemaMember("CSoundEventPathCornerEntity", "m_bPlaying")]
	public ref bool Playing => ref Schema.GetRef<bool>(this.Handle, "CSoundEventPathCornerEntity", "m_bPlaying");

}
