// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CTriggerDetectBulletFire : CBaseTrigger
{
    public CTriggerDetectBulletFire (IntPtr pointer) : base(pointer) {}

	// m_bPlayerFireOnly
	[SchemaMember("CTriggerDetectBulletFire", "m_bPlayerFireOnly")]
	public ref bool PlayerFireOnly => ref Schema.GetRef<bool>(this.Handle, "CTriggerDetectBulletFire", "m_bPlayerFireOnly");

	// m_OnDetectedBulletFire
	[SchemaMember("CTriggerDetectBulletFire", "m_OnDetectedBulletFire")]
	public CEntityIOOutput OnDetectedBulletFire => Schema.GetDeclaredClass<CEntityIOOutput>(this.Handle, "CTriggerDetectBulletFire", "m_OnDetectedBulletFire");

}
