// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class CWeaponBaseItem : CCSWeaponBase
{
    public CWeaponBaseItem (IntPtr pointer) : base(pointer) {}

	// m_bSequenceInProgress
	[SchemaMember("CWeaponBaseItem", "m_bSequenceInProgress")]
	public ref bool SequenceInProgress => ref Schema.GetRef<bool>(this.Handle, "CWeaponBaseItem", "m_bSequenceInProgress");

	// m_bRedraw
	[SchemaMember("CWeaponBaseItem", "m_bRedraw")]
	public ref bool Redraw => ref Schema.GetRef<bool>(this.Handle, "CWeaponBaseItem", "m_bRedraw");

}
