// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class EntityRenderAttribute_t : NativeObject
{
    public EntityRenderAttribute_t (IntPtr pointer) : base(pointer) {}

	// m_ID
	[SchemaMember("EntityRenderAttribute_t", "m_ID")]
	public CUtlStringToken ID => Schema.GetDeclaredClass<CUtlStringToken>(this.Handle, "EntityRenderAttribute_t", "m_ID");

	// m_Values
	[SchemaMember("EntityRenderAttribute_t", "m_Values")]
	public Vector4 Values
	{
		get { return Schema.GetValueType<Vector4>(this.Handle, "EntityRenderAttribute_t", "m_Values"); }
		set { Schema.SetValueType<Vector4>(this.Handle, "EntityRenderAttribute_t", "m_Values", value); }
	}

	public void IDPropertyChanged() => Utilities.SetStateChanged(this, "EntityRenderAttribute_t", "m_ID");
	public void ValuesPropertyChanged() => Utilities.SetStateChanged(this, "EntityRenderAttribute_t", "m_Values");
}
