// <auto-generated />
#nullable enable
#pragma warning disable CS1591

using System;
using System.Diagnostics;
using System.Drawing;
using System.Numerics;
using CounterStrikeSharp;
using CounterStrikeSharp.API.Modules.Events;
using CounterStrikeSharp.API.Modules.Entities;
using CounterStrikeSharp.API.Modules.Memory;
using CounterStrikeSharp.API.Modules.Utils;
using CounterStrikeSharp.API.Core.Attributes;

namespace CounterStrikeSharp.API.Core;

public partial class IntervalTimer : NativeObject
{
    public IntervalTimer (IntPtr pointer) : base(pointer) {}

	// m_timestamp
	[SchemaMember("IntervalTimer", "m_timestamp")]
	public float Timestamp
	{
		get { return Schema.GetValueType<float>(this.Handle, "IntervalTimer", "m_timestamp"); }
		set { Schema.SetValueType<float>(this.Handle, "IntervalTimer", "m_timestamp", value); }
	}

	// m_nWorldGroupId
	[SchemaMember("IntervalTimer", "m_nWorldGroupId")]
	public WorldGroupId_t WorldGroupId => Schema.GetDeclaredClass<WorldGroupId_t>(this.Handle, "IntervalTimer", "m_nWorldGroupId");

	public void TimestampPropertyChanged() => Utilities.SetStateChanged(this, "IntervalTimer", "m_timestamp");
	public void WorldGroupIdPropertyChanged() => Utilities.SetStateChanged(this, "IntervalTimer", "m_nWorldGroupId");
}
