name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [ "win32" ]
  
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare env
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

        
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - run: dotnet publish -c Release managed/CounterStrikeSharp.API

      - name: Install Protoc
        uses: arduino/setup-protoc@v2


      - name: Build Linux
        if: runner.os == 'Linux'
        run: |
          cd ${{github.workspace}}
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
          cmake --build . --config ${{env.BUILD_TYPE}}