name: Sync with upstream

on:
  schedule:
    - cron: "0 3 * * *"   # codziennie o 3:00 w nocy
  workflow_dispatch:       # rêczne uruchomienie

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/roflmuffin/CounterStrikeSharp.git || true
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main || true
